// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseWallet is an autogenerated mock type for the UsecaseWallet type
type MockUsecaseWallet struct {
	mock.Mock
}

type MockUsecaseWallet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseWallet) EXPECT() *MockUsecaseWallet_Expecter {
	return &MockUsecaseWallet_Expecter{mock: &_m.Mock}
}

// Wallet provides a mock function with given fields: ctx, accountID, limit
func (_m *MockUsecaseWallet) Wallet(ctx context.Context, accountID uuid.UUID, limit int) (biz.WalletView, error) {
	ret := _m.Called(ctx, accountID, limit)

	if len(ret) == 0 {
		panic("no return value specified for Wallet")
	}

	var r0 biz.WalletView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (biz.WalletView, error)); ok {
		return rf(ctx, accountID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) biz.WalletView); ok {
		r0 = rf(ctx, accountID, limit)
	} else {
		r0 = ret.Get(0).(biz.WalletView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, accountID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseWallet_Wallet_Call struct {
	*mock.Call
}

func (_e *MockUsecaseWallet_Expecter) Wallet(ctx interface{}, accountID interface{}, limit interface{}) *MockUsecaseWallet_Wallet_Call {
	return &MockUsecaseWallet_Wallet_Call{Call: _e.mock.On("Wallet", ctx, accountID, limit)}
}

func (_c *MockUsecaseWallet_Wallet_Call) Run(run func(ctx context.Context, accountID uuid.UUID, limit int)) *MockUsecaseWallet_Wallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockUsecaseWallet_Wallet_Call) Return(_a0 biz.WalletView, _a1 error) *MockUsecaseWallet_Wallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseWallet_Wallet_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (biz.WalletView, error)) *MockUsecaseWallet_Wallet_Call {
	_c.Call.Return(run)
	return _c
}

// Packages provides a mock function with given fields: ctx
func (_m *MockUsecaseWallet) Packages(ctx context.Context) ([]entity.BidPackage, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Packages")
	}

	var r0 []entity.BidPackage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.BidPackage, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.BidPackage); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BidPackage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseWallet_Packages_Call struct {
	*mock.Call
}

func (_e *MockUsecaseWallet_Expecter) Packages(ctx interface{}) *MockUsecaseWallet_Packages_Call {
	return &MockUsecaseWallet_Packages_Call{Call: _e.mock.On("Packages", ctx)}
}

func (_c *MockUsecaseWallet_Packages_Call) Run(run func(ctx context.Context)) *MockUsecaseWallet_Packages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsecaseWallet_Packages_Call) Return(_a0 []entity.BidPackage, _a1 error) *MockUsecaseWallet_Packages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseWallet_Packages_Call) RunAndReturn(run func(context.Context) ([]entity.BidPackage, error)) *MockUsecaseWallet_Packages_Call {
	_c.Call.Return(run)
	return _c
}

// Buy provides a mock function with given fields: ctx, accountID, packageID, idempotencyKey
func (_m *MockUsecaseWallet) Buy(ctx context.Context, accountID uuid.UUID, packageID string, idempotencyKey string) (biz.PurchaseResult, error) {
	ret := _m.Called(ctx, accountID, packageID, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Buy")
	}

	var r0 biz.PurchaseResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (biz.PurchaseResult, error)); ok {
		return rf(ctx, accountID, packageID, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) biz.PurchaseResult); ok {
		r0 = rf(ctx, accountID, packageID, idempotencyKey)
	} else {
		r0 = ret.Get(0).(biz.PurchaseResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, accountID, packageID, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseWallet_Buy_Call struct {
	*mock.Call
}

func (_e *MockUsecaseWallet_Expecter) Buy(ctx interface{}, accountID interface{}, packageID interface{}, idempotencyKey interface{}) *MockUsecaseWallet_Buy_Call {
	return &MockUsecaseWallet_Buy_Call{Call: _e.mock.On("Buy", ctx, accountID, packageID, idempotencyKey)}
}

func (_c *MockUsecaseWallet_Buy_Call) Run(run func(ctx context.Context, accountID uuid.UUID, packageID string, idempotencyKey string)) *MockUsecaseWallet_Buy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUsecaseWallet_Buy_Call) Return(_a0 biz.PurchaseResult, _a1 error) *MockUsecaseWallet_Buy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseWallet_Buy_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (biz.PurchaseResult, error)) *MockUsecaseWallet_Buy_Call {
	_c.Call.Return(run)
	return _c
}

// Debit provides a mock function with given fields: ctx, accountID, amount, idempotencyKey, auctionID
func (_m *MockUsecaseWallet) Debit(ctx context.Context, accountID uuid.UUID, amount int64, idempotencyKey string, auctionID string) (biz.DebitResult, error) {
	ret := _m.Called(ctx, accountID, amount, idempotencyKey, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for Debit")
	}

	var r0 biz.DebitResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, string, string) (biz.DebitResult, error)); ok {
		return rf(ctx, accountID, amount, idempotencyKey, auctionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, string, string) biz.DebitResult); ok {
		r0 = rf(ctx, accountID, amount, idempotencyKey, auctionID)
	} else {
		r0 = ret.Get(0).(biz.DebitResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64, string, string) error); ok {
		r1 = rf(ctx, accountID, amount, idempotencyKey, auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseWallet_Debit_Call struct {
	*mock.Call
}

func (_e *MockUsecaseWallet_Expecter) Debit(ctx interface{}, accountID interface{}, amount interface{}, idempotencyKey interface{}, auctionID interface{}) *MockUsecaseWallet_Debit_Call {
	return &MockUsecaseWallet_Debit_Call{Call: _e.mock.On("Debit", ctx, accountID, amount, idempotencyKey, auctionID)}
}

func (_c *MockUsecaseWallet_Debit_Call) Run(run func(ctx context.Context, accountID uuid.UUID, amount int64, idempotencyKey string, auctionID string)) *MockUsecaseWallet_Debit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockUsecaseWallet_Debit_Call) Return(_a0 biz.DebitResult, _a1 error) *MockUsecaseWallet_Debit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseWallet_Debit_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64, string, string) (biz.DebitResult, error)) *MockUsecaseWallet_Debit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseWallet creates a new instance of MockUsecaseWallet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseWallet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseWallet {
	mock := &MockUsecaseWallet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
