// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryWallet is an autogenerated mock type for the RepositoryWallet type
type MockRepositoryWallet struct {
	mock.Mock
}

type MockRepositoryWallet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryWallet) EXPECT() *MockRepositoryWallet_Expecter {
	return &MockRepositoryWallet_Expecter{mock: &_m.Mock}
}

// GetWallet provides a mock function with given fields: ctx, accountID
func (_m *MockRepositoryWallet) GetWallet(ctx context.Context, accountID uuid.UUID) (entity.BidWallet, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetWallet")
	}

	var r0 entity.BidWallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.BidWallet, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.BidWallet); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(entity.BidWallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockRepositoryWallet_GetWallet_Call struct {
	*mock.Call
}

func (_e *MockRepositoryWallet_Expecter) GetWallet(ctx interface{}, accountID interface{}) *MockRepositoryWallet_GetWallet_Call {
	return &MockRepositoryWallet_GetWallet_Call{Call: _e.mock.On("GetWallet", ctx, accountID)}
}

func (_c *MockRepositoryWallet_GetWallet_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockRepositoryWallet_GetWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryWallet_GetWallet_Call) Return(_a0 entity.BidWallet, _a1 error) *MockRepositoryWallet_GetWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryWallet_GetWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.BidWallet, error)) *MockRepositoryWallet_GetWallet_Call {
	_c.Call.Return(run)
	return _c
}

// RecentPurchases provides a mock function with given fields: ctx, accountID, limit
func (_m *MockRepositoryWallet) RecentPurchases(ctx context.Context, accountID uuid.UUID, limit int) ([]entity.BidPurchase, error) {
	ret := _m.Called(ctx, accountID, limit)

	if len(ret) == 0 {
		panic("no return value specified for RecentPurchases")
	}

	var r0 []entity.BidPurchase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]entity.BidPurchase, error)); ok {
		return rf(ctx, accountID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []entity.BidPurchase); ok {
		r0 = rf(ctx, accountID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BidPurchase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, accountID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockRepositoryWallet_RecentPurchases_Call struct {
	*mock.Call
}

func (_e *MockRepositoryWallet_Expecter) RecentPurchases(ctx interface{}, accountID interface{}, limit interface{}) *MockRepositoryWallet_RecentPurchases_Call {
	return &MockRepositoryWallet_RecentPurchases_Call{Call: _e.mock.On("RecentPurchases", ctx, accountID, limit)}
}

func (_c *MockRepositoryWallet_RecentPurchases_Call) Run(run func(ctx context.Context, accountID uuid.UUID, limit int)) *MockRepositoryWallet_RecentPurchases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockRepositoryWallet_RecentPurchases_Call) Return(_a0 []entity.BidPurchase, _a1 error) *MockRepositoryWallet_RecentPurchases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryWallet_RecentPurchases_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]entity.BidPurchase, error)) *MockRepositoryWallet_RecentPurchases_Call {
	_c.Call.Return(run)
	return _c
}

// RecentDebits provides a mock function with given fields: ctx, accountID, limit
func (_m *MockRepositoryWallet) RecentDebits(ctx context.Context, accountID uuid.UUID, limit int) ([]entity.BidDebit, error) {
	ret := _m.Called(ctx, accountID, limit)

	if len(ret) == 0 {
		panic("no return value specified for RecentDebits")
	}

	var r0 []entity.BidDebit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]entity.BidDebit, error)); ok {
		return rf(ctx, accountID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []entity.BidDebit); ok {
		r0 = rf(ctx, accountID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BidDebit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, accountID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockRepositoryWallet_RecentDebits_Call struct {
	*mock.Call
}

func (_e *MockRepositoryWallet_Expecter) RecentDebits(ctx interface{}, accountID interface{}, limit interface{}) *MockRepositoryWallet_RecentDebits_Call {
	return &MockRepositoryWallet_RecentDebits_Call{Call: _e.mock.On("RecentDebits", ctx, accountID, limit)}
}

func (_c *MockRepositoryWallet_RecentDebits_Call) Run(run func(ctx context.Context, accountID uuid.UUID, limit int)) *MockRepositoryWallet_RecentDebits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockRepositoryWallet_RecentDebits_Call) Return(_a0 []entity.BidDebit, _a1 error) *MockRepositoryWallet_RecentDebits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryWallet_RecentDebits_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]entity.BidDebit, error)) *MockRepositoryWallet_RecentDebits_Call {
	_c.Call.Return(run)
	return _c
}

// ListPackages provides a mock function with given fields: ctx
func (_m *MockRepositoryWallet) ListPackages(ctx context.Context) ([]entity.BidPackage, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPackages")
	}

	var r0 []entity.BidPackage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.BidPackage, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.BidPackage); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BidPackage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockRepositoryWallet_ListPackages_Call struct {
	*mock.Call
}

func (_e *MockRepositoryWallet_Expecter) ListPackages(ctx interface{}) *MockRepositoryWallet_ListPackages_Call {
	return &MockRepositoryWallet_ListPackages_Call{Call: _e.mock.On("ListPackages", ctx)}
}

func (_c *MockRepositoryWallet_ListPackages_Call) Run(run func(ctx context.Context)) *MockRepositoryWallet_ListPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryWallet_ListPackages_Call) Return(_a0 []entity.BidPackage, _a1 error) *MockRepositoryWallet_ListPackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryWallet_ListPackages_Call) RunAndReturn(run func(context.Context) ([]entity.BidPackage, error)) *MockRepositoryWallet_ListPackages_Call {
	_c.Call.Return(run)
	return _c
}

// GetPackage provides a mock function with given fields: ctx, id
func (_m *MockRepositoryWallet) GetPackage(ctx context.Context, id string) (entity.BidPackage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPackage")
	}

	var r0 entity.BidPackage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.BidPackage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.BidPackage); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.BidPackage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockRepositoryWallet_GetPackage_Call struct {
	*mock.Call
}

func (_e *MockRepositoryWallet_Expecter) GetPackage(ctx interface{}, id interface{}) *MockRepositoryWallet_GetPackage_Call {
	return &MockRepositoryWallet_GetPackage_Call{Call: _e.mock.On("GetPackage", ctx, id)}
}

func (_c *MockRepositoryWallet_GetPackage_Call) Run(run func(ctx context.Context, id string)) *MockRepositoryWallet_GetPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryWallet_GetPackage_Call) Return(_a0 entity.BidPackage, _a1 error) *MockRepositoryWallet_GetPackage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryWallet_GetPackage_Call) RunAndReturn(run func(context.Context, string) (entity.BidPackage, error)) *MockRepositoryWallet_GetPackage_Call {
	_c.Call.Return(run)
	return _c
}

// GrantTx provides a mock function with given fields: ctx, purchase, idempotencyKey, outbox
func (_m *MockRepositoryWallet) GrantTx(ctx context.Context, purchase entity.BidPurchase, idempotencyKey string, outbox entity.OutboxEvent) (biz.PurchaseResult, error) {
	ret := _m.Called(ctx, purchase, idempotencyKey, outbox)

	if len(ret) == 0 {
		panic("no return value specified for GrantTx")
	}

	var r0 biz.PurchaseResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.BidPurchase, string, entity.OutboxEvent) (biz.PurchaseResult, error)); ok {
		return rf(ctx, purchase, idempotencyKey, outbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.BidPurchase, string, entity.OutboxEvent) biz.PurchaseResult); ok {
		r0 = rf(ctx, purchase, idempotencyKey, outbox)
	} else {
		r0 = ret.Get(0).(biz.PurchaseResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.BidPurchase, string, entity.OutboxEvent) error); ok {
		r1 = rf(ctx, purchase, idempotencyKey, outbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockRepositoryWallet_GrantTx_Call struct {
	*mock.Call
}

func (_e *MockRepositoryWallet_Expecter) GrantTx(ctx interface{}, purchase interface{}, idempotencyKey interface{}, outbox interface{}) *MockRepositoryWallet_GrantTx_Call {
	return &MockRepositoryWallet_GrantTx_Call{Call: _e.mock.On("GrantTx", ctx, purchase, idempotencyKey, outbox)}
}

func (_c *MockRepositoryWallet_GrantTx_Call) Run(run func(ctx context.Context, purchase entity.BidPurchase, idempotencyKey string, outbox entity.OutboxEvent)) *MockRepositoryWallet_GrantTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.BidPurchase), args[2].(string), args[3].(entity.OutboxEvent))
	})
	return _c
}

func (_c *MockRepositoryWallet_GrantTx_Call) Return(result biz.PurchaseResult, err error) *MockRepositoryWallet_GrantTx_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockRepositoryWallet_GrantTx_Call) RunAndReturn(run func(context.Context, entity.BidPurchase, string, entity.OutboxEvent) (biz.PurchaseResult, error)) *MockRepositoryWallet_GrantTx_Call {
	_c.Call.Return(run)
	return _c
}

// DebitTx provides a mock function with given fields: ctx, debit
func (_m *MockRepositoryWallet) DebitTx(ctx context.Context, debit entity.BidDebit) (biz.DebitResult, bool, error) {
	ret := _m.Called(ctx, debit)

	if len(ret) == 0 {
		panic("no return value specified for DebitTx")
	}

	var r0 biz.DebitResult
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.BidDebit) (biz.DebitResult, bool, error)); ok {
		return rf(ctx, debit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.BidDebit) biz.DebitResult); ok {
		r0 = rf(ctx, debit)
	} else {
		r0 = ret.Get(0).(biz.DebitResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.BidDebit) bool); ok {
		r1 = rf(ctx, debit)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.BidDebit) error); ok {
		r2 = rf(ctx, debit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type MockRepositoryWallet_DebitTx_Call struct {
	*mock.Call
}

func (_e *MockRepositoryWallet_Expecter) DebitTx(ctx interface{}, debit interface{}) *MockRepositoryWallet_DebitTx_Call {
	return &MockRepositoryWallet_DebitTx_Call{Call: _e.mock.On("DebitTx", ctx, debit)}
}

func (_c *MockRepositoryWallet_DebitTx_Call) Run(run func(ctx context.Context, debit entity.BidDebit)) *MockRepositoryWallet_DebitTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.BidDebit))
	})
	return _c
}

func (_c *MockRepositoryWallet_DebitTx_Call) Return(result biz.DebitResult, fresh bool, err error) *MockRepositoryWallet_DebitTx_Call {
	_c.Call.Return(result, fresh, err)
	return _c
}

func (_c *MockRepositoryWallet_DebitTx_Call) RunAndReturn(run func(context.Context, entity.BidDebit) (biz.DebitResult, bool, error)) *MockRepositoryWallet_DebitTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryWallet creates a new instance of MockRepositoryWallet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryWallet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryWallet {
	mock := &MockRepositoryWallet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
