// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/app"
	"application/internal/biz"
	"application/internal/datasource"
	"application/internal/eventbus"
	"application/internal/repo"
	"application/internal/service"
	"application/internal/service/handler"
	"context"
	"net/http"
)

// Injectors from wire.go:

func wireApp(ctx context.Context) (app.Application, error) {
	runTimeFlags := app.NewRunTimeFlags()
	kConfig, err := app.NewKoanfConfig(runTimeFlags)
	if err != nil {
		return nil, err
	}
	appConfig, err := app.NewAppConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	httpServerConfig, err := app.NewHTTPServerConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	appLoggerConfig, err := app.NewAppLoggerConfig(kConfig)
	if err != nil {
		return nil, err
	}
	collectorConfig, err := app.NewCollectorConfig(ctx, kConfig)
	if err != nil {
		return nil, err
	}
	controller := app.NewController()
	otlp, err := app.NewOTLP(ctx, collectorConfig, appConfig, controller, httpServerConfig)
	if err != nil {
		return nil, err
	}
	appLogger, err := app.NewAppLogger(ctx, appConfig, appLoggerConfig, otlp)
	if err != nil {
		return nil, err
	}
	logger := app.NewSlogLogger(appLogger)
	serveMux := http.NewServeMux()
	healthz := biz.NewHealthz(logger, controller)
	healthzHandler := handler.NewMuxHealthzHandler(healthz, logger, serveMux)
	postgresDB, err := datasource.NewPostgresDB(ctx, logger, kConfig, controller)
	if err != nil {
		return nil, err
	}
	lot := repo.NewLot(logger, postgresDB)
	bizLot := biz.NewLot(logger, lot)
	lotHandler := handler.NewLotHandler(logger, serveMux, bizLot)
	nats, err := datasource.NewNats(ctx, logger, kConfig, controller)
	if err != nil {
		return nil, err
	}
	outbox := repo.NewOutbox(logger, postgresDB)
	outboxPublisher := biz.NewOutboxPublisher(logger, outbox, nats)
	eventConsumer := biz.NewEventConsumer(logger, bizLot)
	runner := eventbus.NewRunner(logger, nats, outboxPublisher, eventConsumer, controller)
	v := handler.NewServiceList(healthzHandler, lotHandler, runner)
	httpHandler, err := service.NewHTTPHandler(ctx, logger, serveMux, v...)
	if err != nil {
		return nil, err
	}
	httpServer := app.NewHTTPServer(httpServerConfig, httpHandler, appLogger)
	appApp := app.NewApp(runTimeFlags, appConfig, httpServer, appLogger, controller)
	return appApp, nil
}
