// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseVault is an autogenerated mock type for the UsecaseVault type
type MockUsecaseVault struct {
	mock.Mock
}

type MockUsecaseVault_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseVault) EXPECT() *MockUsecaseVault_Expecter {
	return &MockUsecaseVault_Expecter{mock: &_m.Mock}
}

// View provides a mock function with given fields: ctx, owner
func (_m *MockUsecaseVault) View(ctx context.Context, owner uuid.UUID) (biz.VaultView, error) {
	ret := _m.Called(ctx, owner)

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 biz.VaultView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (biz.VaultView, error)); ok {
		return rf(ctx, owner)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) biz.VaultView); ok {
		r0 = rf(ctx, owner)
	} else {
		r0 = ret.Get(0).(biz.VaultView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseVault_View_Call struct {
	*mock.Call
}

func (_e *MockUsecaseVault_Expecter) View(ctx interface{}, owner interface{}) *MockUsecaseVault_View_Call {
	return &MockUsecaseVault_View_Call{Call: _e.mock.On("View", ctx, owner)}
}

func (_c *MockUsecaseVault_View_Call) Run(run func(ctx context.Context, owner uuid.UUID)) *MockUsecaseVault_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseVault_View_Call) Return(_a0 biz.VaultView, _a1 error) *MockUsecaseVault_View_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseVault_View_Call) RunAndReturn(run func(context.Context, uuid.UUID) (biz.VaultView, error)) *MockUsecaseVault_View_Call {
	_c.Call.Return(run)
	return _c
}

// AddObject provides a mock function with given fields: ctx, owner, title, description, appraisedValueCents
func (_m *MockUsecaseVault) AddObject(ctx context.Context, owner uuid.UUID, title string, description string, appraisedValueCents int64) (entity.VaultObject, error) {
	ret := _m.Called(ctx, owner, title, description, appraisedValueCents)

	if len(ret) == 0 {
		panic("no return value specified for AddObject")
	}

	var r0 entity.VaultObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int64) (entity.VaultObject, error)); ok {
		return rf(ctx, owner, title, description, appraisedValueCents)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int64) entity.VaultObject); ok {
		r0 = rf(ctx, owner, title, description, appraisedValueCents)
	} else {
		r0 = ret.Get(0).(entity.VaultObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, int64) error); ok {
		r1 = rf(ctx, owner, title, description, appraisedValueCents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseVault_AddObject_Call struct {
	*mock.Call
}

func (_e *MockUsecaseVault_Expecter) AddObject(ctx interface{}, owner interface{}, title interface{}, description interface{}, appraisedValueCents interface{}) *MockUsecaseVault_AddObject_Call {
	return &MockUsecaseVault_AddObject_Call{Call: _e.mock.On("AddObject", ctx, owner, title, description, appraisedValueCents)}
}

func (_c *MockUsecaseVault_AddObject_Call) Run(run func(ctx context.Context, owner uuid.UUID, title string, description string, appraisedValueCents int64)) *MockUsecaseVault_AddObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(int64))
	})
	return _c
}

func (_c *MockUsecaseVault_AddObject_Call) Return(_a0 entity.VaultObject, _a1 error) *MockUsecaseVault_AddObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseVault_AddObject_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, int64) (entity.VaultObject, error)) *MockUsecaseVault_AddObject_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, owner, objectID, req
func (_m *MockUsecaseVault) List(ctx context.Context, owner uuid.UUID, objectID uuid.UUID, req biz.ListRequest) (entity.VaultObject, error) {
	ret := _m.Called(ctx, owner, objectID, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 entity.VaultObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, biz.ListRequest) (entity.VaultObject, error)); ok {
		return rf(ctx, owner, objectID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, biz.ListRequest) entity.VaultObject); ok {
		r0 = rf(ctx, owner, objectID, req)
	} else {
		r0 = ret.Get(0).(entity.VaultObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, biz.ListRequest) error); ok {
		r1 = rf(ctx, owner, objectID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseVault_List_Call struct {
	*mock.Call
}

func (_e *MockUsecaseVault_Expecter) List(ctx interface{}, owner interface{}, objectID interface{}, req interface{}) *MockUsecaseVault_List_Call {
	return &MockUsecaseVault_List_Call{Call: _e.mock.On("List", ctx, owner, objectID, req)}
}

func (_c *MockUsecaseVault_List_Call) Run(run func(ctx context.Context, owner uuid.UUID, objectID uuid.UUID, req biz.ListRequest)) *MockUsecaseVault_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(biz.ListRequest))
	})
	return _c
}

func (_c *MockUsecaseVault_List_Call) Return(_a0 entity.VaultObject, _a1 error) *MockUsecaseVault_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseVault_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, biz.ListRequest) (entity.VaultObject, error)) *MockUsecaseVault_List_Call {
	_c.Call.Return(run)
	return _c
}

// Buyback provides a mock function with given fields: ctx, owner, objectID, mode
func (_m *MockUsecaseVault) Buyback(ctx context.Context, owner uuid.UUID, objectID uuid.UUID, mode entity.BuybackMode) (biz.BuybackResult, error) {
	ret := _m.Called(ctx, owner, objectID, mode)

	if len(ret) == 0 {
		panic("no return value specified for Buyback")
	}

	var r0 biz.BuybackResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, entity.BuybackMode) (biz.BuybackResult, error)); ok {
		return rf(ctx, owner, objectID, mode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, entity.BuybackMode) biz.BuybackResult); ok {
		r0 = rf(ctx, owner, objectID, mode)
	} else {
		r0 = ret.Get(0).(biz.BuybackResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, entity.BuybackMode) error); ok {
		r1 = rf(ctx, owner, objectID, mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseVault_Buyback_Call struct {
	*mock.Call
}

func (_e *MockUsecaseVault_Expecter) Buyback(ctx interface{}, owner interface{}, objectID interface{}, mode interface{}) *MockUsecaseVault_Buyback_Call {
	return &MockUsecaseVault_Buyback_Call{Call: _e.mock.On("Buyback", ctx, owner, objectID, mode)}
}

func (_c *MockUsecaseVault_Buyback_Call) Run(run func(ctx context.Context, owner uuid.UUID, objectID uuid.UUID, mode entity.BuybackMode)) *MockUsecaseVault_Buyback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(entity.BuybackMode))
	})
	return _c
}

func (_c *MockUsecaseVault_Buyback_Call) Return(_a0 biz.BuybackResult, _a1 error) *MockUsecaseVault_Buyback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseVault_Buyback_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, entity.BuybackMode) (biz.BuybackResult, error)) *MockUsecaseVault_Buyback_Call {
	_c.Call.Return(run)
	return _c
}

// SettleAuctionCompleted provides a mock function with given fields: ctx, in
func (_m *MockUsecaseVault) SettleAuctionCompleted(ctx context.Context, in biz.AuctionCompletedInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for SettleAuctionCompleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.AuctionCompletedInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockUsecaseVault_SettleAuctionCompleted_Call struct {
	*mock.Call
}

func (_e *MockUsecaseVault_Expecter) SettleAuctionCompleted(ctx interface{}, in interface{}) *MockUsecaseVault_SettleAuctionCompleted_Call {
	return &MockUsecaseVault_SettleAuctionCompleted_Call{Call: _e.mock.On("SettleAuctionCompleted", ctx, in)}
}

func (_c *MockUsecaseVault_SettleAuctionCompleted_Call) Run(run func(ctx context.Context, in biz.AuctionCompletedInput)) *MockUsecaseVault_SettleAuctionCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.AuctionCompletedInput))
	})
	return _c
}

func (_c *MockUsecaseVault_SettleAuctionCompleted_Call) Return(_a0 error) *MockUsecaseVault_SettleAuctionCompleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseVault_SettleAuctionCompleted_Call) RunAndReturn(run func(context.Context, biz.AuctionCompletedInput) error) *MockUsecaseVault_SettleAuctionCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseVault creates a new instance of MockUsecaseVault. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseVault(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseVault {
	mock := &MockUsecaseVault{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
