// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	context "context"

	entity "application/internal/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryVault is an autogenerated mock type for the RepositoryVault type
type MockRepositoryVault struct {
	mock.Mock
}

type MockRepositoryVault_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryVault) EXPECT() *MockRepositoryVault_Expecter {
	return &MockRepositoryVault_Expecter{mock: &_m.Mock}
}

// BuybackTx provides a mock function with given fields: ctx, objectID, entry, buildOutbox
func (_m *MockRepositoryVault) BuybackTx(ctx context.Context, objectID uuid.UUID, entry *entity.VaultCreditEntry, buildOutbox biz.OutboxBuilder) (entity.VaultObject, int64, error) {
	ret := _m.Called(ctx, objectID, entry, buildOutbox)

	if len(ret) == 0 {
		panic("no return value specified for BuybackTx")
	}

	var r0 entity.VaultObject
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.VaultCreditEntry, biz.OutboxBuilder) (entity.VaultObject, int64, error)); ok {
		return rf(ctx, objectID, entry, buildOutbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.VaultCreditEntry, biz.OutboxBuilder) entity.VaultObject); ok {
		r0 = rf(ctx, objectID, entry, buildOutbox)
	} else {
		r0 = ret.Get(0).(entity.VaultObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *entity.VaultCreditEntry, biz.OutboxBuilder) int64); ok {
		r1 = rf(ctx, objectID, entry, buildOutbox)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, *entity.VaultCreditEntry, biz.OutboxBuilder) error); ok {
		r2 = rf(ctx, objectID, entry, buildOutbox)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepositoryVault_BuybackTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuybackTx'
type MockRepositoryVault_BuybackTx_Call struct {
	*mock.Call
}

// BuybackTx is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID uuid.UUID
//   - entry *entity.VaultCreditEntry
//   - buildOutbox biz.OutboxBuilder
func (_e *MockRepositoryVault_Expecter) BuybackTx(ctx interface{}, objectID interface{}, entry interface{}, buildOutbox interface{}) *MockRepositoryVault_BuybackTx_Call {
	return &MockRepositoryVault_BuybackTx_Call{Call: _e.mock.On("BuybackTx", ctx, objectID, entry, buildOutbox)}
}

func (_c *MockRepositoryVault_BuybackTx_Call) Run(run func(ctx context.Context, objectID uuid.UUID, entry *entity.VaultCreditEntry, buildOutbox biz.OutboxBuilder)) *MockRepositoryVault_BuybackTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.VaultCreditEntry), args[3].(biz.OutboxBuilder))
	})
	return _c
}

func (_c *MockRepositoryVault_BuybackTx_Call) Return(_a0 entity.VaultObject, _a1 int64, _a2 error) *MockRepositoryVault_BuybackTx_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepositoryVault_BuybackTx_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.VaultCreditEntry, biz.OutboxBuilder) (entity.VaultObject, int64, error)) *MockRepositoryVault_BuybackTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreditBalance provides a mock function with given fields: ctx, account
func (_m *MockRepositoryVault) CreditBalance(ctx context.Context, account uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for CreditBalance")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryVault_CreditBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreditBalance'
type MockRepositoryVault_CreditBalance_Call struct {
	*mock.Call
}

// CreditBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - account uuid.UUID
func (_e *MockRepositoryVault_Expecter) CreditBalance(ctx interface{}, account interface{}) *MockRepositoryVault_CreditBalance_Call {
	return &MockRepositoryVault_CreditBalance_Call{Call: _e.mock.On("CreditBalance", ctx, account)}
}

func (_c *MockRepositoryVault_CreditBalance_Call) Run(run func(ctx context.Context, account uuid.UUID)) *MockRepositoryVault_CreditBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryVault_CreditBalance_Call) Return(_a0 int64, _a1 error) *MockRepositoryVault_CreditBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryVault_CreditBalance_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockRepositoryVault_CreditBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function with given fields: ctx, objectID
func (_m *MockRepositoryVault) GetObject(ctx context.Context, objectID uuid.UUID) (entity.VaultObject, error) {
	ret := _m.Called(ctx, objectID)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 entity.VaultObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.VaultObject, error)); ok {
		return rf(ctx, objectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.VaultObject); ok {
		r0 = rf(ctx, objectID)
	} else {
		r0 = ret.Get(0).(entity.VaultObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, objectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryVault_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockRepositoryVault_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID uuid.UUID
func (_e *MockRepositoryVault_Expecter) GetObject(ctx interface{}, objectID interface{}) *MockRepositoryVault_GetObject_Call {
	return &MockRepositoryVault_GetObject_Call{Call: _e.mock.On("GetObject", ctx, objectID)}
}

func (_c *MockRepositoryVault_GetObject_Call) Run(run func(ctx context.Context, objectID uuid.UUID)) *MockRepositoryVault_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryVault_GetObject_Call) Return(_a0 entity.VaultObject, _a1 error) *MockRepositoryVault_GetObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryVault_GetObject_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.VaultObject, error)) *MockRepositoryVault_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// InsertObject provides a mock function with given fields: ctx, obj
func (_m *MockRepositoryVault) InsertObject(ctx context.Context, obj entity.VaultObject) (entity.VaultObject, error) {
	ret := _m.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for InsertObject")
	}

	var r0 entity.VaultObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.VaultObject) (entity.VaultObject, error)); ok {
		return rf(ctx, obj)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.VaultObject) entity.VaultObject); ok {
		r0 = rf(ctx, obj)
	} else {
		r0 = ret.Get(0).(entity.VaultObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.VaultObject) error); ok {
		r1 = rf(ctx, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryVault_InsertObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertObject'
type MockRepositoryVault_InsertObject_Call struct {
	*mock.Call
}

// InsertObject is a helper method to define mock.On call
//   - ctx context.Context
//   - obj entity.VaultObject
func (_e *MockRepositoryVault_Expecter) InsertObject(ctx interface{}, obj interface{}) *MockRepositoryVault_InsertObject_Call {
	return &MockRepositoryVault_InsertObject_Call{Call: _e.mock.On("InsertObject", ctx, obj)}
}

func (_c *MockRepositoryVault_InsertObject_Call) Run(run func(ctx context.Context, obj entity.VaultObject)) *MockRepositoryVault_InsertObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.VaultObject))
	})
	return _c
}

func (_c *MockRepositoryVault_InsertObject_Call) Return(_a0 entity.VaultObject, _a1 error) *MockRepositoryVault_InsertObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryVault_InsertObject_Call) RunAndReturn(run func(context.Context, entity.VaultObject) (entity.VaultObject, error)) *MockRepositoryVault_InsertObject_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjects provides a mock function with given fields: ctx, owner
func (_m *MockRepositoryVault) ListObjects(ctx context.Context, owner uuid.UUID) ([]entity.VaultObject, error) {
	ret := _m.Called(ctx, owner)

	if len(ret) == 0 {
		panic("no return value specified for ListObjects")
	}

	var r0 []entity.VaultObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.VaultObject, error)); ok {
		return rf(ctx, owner)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.VaultObject); ok {
		r0 = rf(ctx, owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.VaultObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryVault_ListObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjects'
type MockRepositoryVault_ListObjects_Call struct {
	*mock.Call
}

// ListObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - owner uuid.UUID
func (_e *MockRepositoryVault_Expecter) ListObjects(ctx interface{}, owner interface{}) *MockRepositoryVault_ListObjects_Call {
	return &MockRepositoryVault_ListObjects_Call{Call: _e.mock.On("ListObjects", ctx, owner)}
}

func (_c *MockRepositoryVault_ListObjects_Call) Run(run func(ctx context.Context, owner uuid.UUID)) *MockRepositoryVault_ListObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryVault_ListObjects_Call) Return(_a0 []entity.VaultObject, _a1 error) *MockRepositoryVault_ListObjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryVault_ListObjects_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.VaultObject, error)) *MockRepositoryVault_ListObjects_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithDetailsTx provides a mock function with given fields: ctx, objectID, from, to, details, outbox
func (_m *MockRepositoryVault) ListWithDetailsTx(ctx context.Context, objectID uuid.UUID, from entity.ObjectState, to entity.ObjectState, details entity.ListingDetails, outbox entity.OutboxEvent) (entity.VaultObject, error) {
	ret := _m.Called(ctx, objectID, from, to, details, outbox)

	if len(ret) == 0 {
		panic("no return value specified for ListWithDetailsTx")
	}

	var r0 entity.VaultObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.ObjectState, entity.ObjectState, entity.ListingDetails, entity.OutboxEvent) (entity.VaultObject, error)); ok {
		return rf(ctx, objectID, from, to, details, outbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.ObjectState, entity.ObjectState, entity.ListingDetails, entity.OutboxEvent) entity.VaultObject); ok {
		r0 = rf(ctx, objectID, from, to, details, outbox)
	} else {
		r0 = ret.Get(0).(entity.VaultObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.ObjectState, entity.ObjectState, entity.ListingDetails, entity.OutboxEvent) error); ok {
		r1 = rf(ctx, objectID, from, to, details, outbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryVault_ListWithDetailsTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithDetailsTx'
type MockRepositoryVault_ListWithDetailsTx_Call struct {
	*mock.Call
}

// ListWithDetailsTx is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID uuid.UUID
//   - from entity.ObjectState
//   - to entity.ObjectState
//   - details entity.ListingDetails
//   - outbox entity.OutboxEvent
func (_e *MockRepositoryVault_Expecter) ListWithDetailsTx(ctx interface{}, objectID interface{}, from interface{}, to interface{}, details interface{}, outbox interface{}) *MockRepositoryVault_ListWithDetailsTx_Call {
	return &MockRepositoryVault_ListWithDetailsTx_Call{Call: _e.mock.On("ListWithDetailsTx", ctx, objectID, from, to, details, outbox)}
}

func (_c *MockRepositoryVault_ListWithDetailsTx_Call) Run(run func(ctx context.Context, objectID uuid.UUID, from entity.ObjectState, to entity.ObjectState, details entity.ListingDetails, outbox entity.OutboxEvent)) *MockRepositoryVault_ListWithDetailsTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.ObjectState), args[3].(entity.ObjectState), args[4].(entity.ListingDetails), args[5].(entity.OutboxEvent))
	})
	return _c
}

func (_c *MockRepositoryVault_ListWithDetailsTx_Call) Return(_a0 entity.VaultObject, _a1 error) *MockRepositoryVault_ListWithDetailsTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryVault_ListWithDetailsTx_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.ObjectState, entity.ObjectState, entity.ListingDetails, entity.OutboxEvent) (entity.VaultObject, error)) *MockRepositoryVault_ListWithDetailsTx_Call {
	_c.Call.Return(run)
	return _c
}

// SettleSoldTx provides a mock function with given fields: ctx, objectID, inboxKey, entry, buildOutbox
func (_m *MockRepositoryVault) SettleSoldTx(ctx context.Context, objectID uuid.UUID, inboxKey string, entry *entity.VaultCreditEntry, buildOutbox biz.OutboxBuilder) (int64, error) {
	ret := _m.Called(ctx, objectID, inboxKey, entry, buildOutbox)

	if len(ret) == 0 {
		panic("no return value specified for SettleSoldTx")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *entity.VaultCreditEntry, biz.OutboxBuilder) (int64, error)); ok {
		return rf(ctx, objectID, inboxKey, entry, buildOutbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *entity.VaultCreditEntry, biz.OutboxBuilder) int64); ok {
		r0 = rf(ctx, objectID, inboxKey, entry, buildOutbox)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, *entity.VaultCreditEntry, biz.OutboxBuilder) error); ok {
		r1 = rf(ctx, objectID, inboxKey, entry, buildOutbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryVault_SettleSoldTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SettleSoldTx'
type MockRepositoryVault_SettleSoldTx_Call struct {
	*mock.Call
}

// SettleSoldTx is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID uuid.UUID
//   - inboxKey string
//   - entry *entity.VaultCreditEntry
//   - buildOutbox biz.OutboxBuilder
func (_e *MockRepositoryVault_Expecter) SettleSoldTx(ctx interface{}, objectID interface{}, inboxKey interface{}, entry interface{}, buildOutbox interface{}) *MockRepositoryVault_SettleSoldTx_Call {
	return &MockRepositoryVault_SettleSoldTx_Call{Call: _e.mock.On("SettleSoldTx", ctx, objectID, inboxKey, entry, buildOutbox)}
}

func (_c *MockRepositoryVault_SettleSoldTx_Call) Run(run func(ctx context.Context, objectID uuid.UUID, inboxKey string, entry *entity.VaultCreditEntry, buildOutbox biz.OutboxBuilder)) *MockRepositoryVault_SettleSoldTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(*entity.VaultCreditEntry), args[4].(biz.OutboxBuilder))
	})
	return _c
}

func (_c *MockRepositoryVault_SettleSoldTx_Call) Return(_a0 int64, _a1 error) *MockRepositoryVault_SettleSoldTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryVault_SettleSoldTx_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, *entity.VaultCreditEntry, biz.OutboxBuilder) (int64, error)) *MockRepositoryVault_SettleSoldTx_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionTx provides a mock function with given fields: ctx, objectID, from, to, outbox
func (_m *MockRepositoryVault) TransitionTx(ctx context.Context, objectID uuid.UUID, from entity.ObjectState, to entity.ObjectState, outbox entity.OutboxEvent) (entity.VaultObject, error) {
	ret := _m.Called(ctx, objectID, from, to, outbox)

	if len(ret) == 0 {
		panic("no return value specified for TransitionTx")
	}

	var r0 entity.VaultObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.ObjectState, entity.ObjectState, entity.OutboxEvent) (entity.VaultObject, error)); ok {
		return rf(ctx, objectID, from, to, outbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.ObjectState, entity.ObjectState, entity.OutboxEvent) entity.VaultObject); ok {
		r0 = rf(ctx, objectID, from, to, outbox)
	} else {
		r0 = ret.Get(0).(entity.VaultObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.ObjectState, entity.ObjectState, entity.OutboxEvent) error); ok {
		r1 = rf(ctx, objectID, from, to, outbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryVault_TransitionTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionTx'
type MockRepositoryVault_TransitionTx_Call struct {
	*mock.Call
}

// TransitionTx is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID uuid.UUID
//   - from entity.ObjectState
//   - to entity.ObjectState
//   - outbox entity.OutboxEvent
func (_e *MockRepositoryVault_Expecter) TransitionTx(ctx interface{}, objectID interface{}, from interface{}, to interface{}, outbox interface{}) *MockRepositoryVault_TransitionTx_Call {
	return &MockRepositoryVault_TransitionTx_Call{Call: _e.mock.On("TransitionTx", ctx, objectID, from, to, outbox)}
}

func (_c *MockRepositoryVault_TransitionTx_Call) Run(run func(ctx context.Context, objectID uuid.UUID, from entity.ObjectState, to entity.ObjectState, outbox entity.OutboxEvent)) *MockRepositoryVault_TransitionTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.ObjectState), args[3].(entity.ObjectState), args[4].(entity.OutboxEvent))
	})
	return _c
}

func (_c *MockRepositoryVault_TransitionTx_Call) Return(_a0 entity.VaultObject, _a1 error) *MockRepositoryVault_TransitionTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryVault_TransitionTx_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.ObjectState, entity.ObjectState, entity.OutboxEvent) (entity.VaultObject, error)) *MockRepositoryVault_TransitionTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryVault creates a new instance of MockRepositoryVault. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryVault(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryVault {
	mock := &MockRepositoryVault{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
