// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryOutbox is an autogenerated mock type for the RepositoryOutbox type
type MockRepositoryOutbox struct {
	mock.Mock
}

type MockRepositoryOutbox_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryOutbox) EXPECT() *MockRepositoryOutbox_Expecter {
	return &MockRepositoryOutbox_Expecter{mock: &_m.Mock}
}

// FetchUnpublished provides a mock function with given fields: ctx, limit
func (_m *MockRepositoryOutbox) FetchUnpublished(ctx context.Context, limit int) ([]entity.OutboxEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchUnpublished")
	}

	var r0 []entity.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.OutboxEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.OutboxEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryOutbox_FetchUnpublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUnpublished'
type MockRepositoryOutbox_FetchUnpublished_Call struct {
	*mock.Call
}

// FetchUnpublished is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockRepositoryOutbox_Expecter) FetchUnpublished(ctx interface{}, limit interface{}) *MockRepositoryOutbox_FetchUnpublished_Call {
	return &MockRepositoryOutbox_FetchUnpublished_Call{Call: _e.mock.On("FetchUnpublished", ctx, limit)}
}

func (_c *MockRepositoryOutbox_FetchUnpublished_Call) Run(run func(ctx context.Context, limit int)) *MockRepositoryOutbox_FetchUnpublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepositoryOutbox_FetchUnpublished_Call) Return(_a0 []entity.OutboxEvent, _a1 error) *MockRepositoryOutbox_FetchUnpublished_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryOutbox_FetchUnpublished_Call) RunAndReturn(run func(context.Context, int) ([]entity.OutboxEvent, error)) *MockRepositoryOutbox_FetchUnpublished_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function with given fields: ctx, id
func (_m *MockRepositoryOutbox) MarkPublished(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryOutbox_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type MockRepositoryOutbox_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepositoryOutbox_Expecter) MarkPublished(ctx interface{}, id interface{}) *MockRepositoryOutbox_MarkPublished_Call {
	return &MockRepositoryOutbox_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, id)}
}

func (_c *MockRepositoryOutbox_MarkPublished_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepositoryOutbox_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryOutbox_MarkPublished_Call) Return(_a0 error) *MockRepositoryOutbox_MarkPublished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryOutbox_MarkPublished_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRepositoryOutbox_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryOutbox creates a new instance of MockRepositoryOutbox. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryOutbox(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryOutbox {
	mock := &MockRepositoryOutbox{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
