// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseAuction is an autogenerated mock type for the UsecaseAuction type
type MockUsecaseAuction struct {
	mock.Mock
}

type MockUsecaseAuction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseAuction) EXPECT() *MockUsecaseAuction_Expecter {
	return &MockUsecaseAuction_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUsecaseAuction) Get(ctx context.Context, id uuid.UUID) (entity.Auction, int, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Auction
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Auction, int, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Auction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Auction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) int); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type MockUsecaseAuction_Get_Call struct {
	*mock.Call
}

func (_e *MockUsecaseAuction_Expecter) Get(ctx interface{}, id interface{}) *MockUsecaseAuction_Get_Call {
	return &MockUsecaseAuction_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUsecaseAuction_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseAuction_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAuction_Get_Call) Return(_a0 entity.Auction, _a1 int, _a2 error) *MockUsecaseAuction_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUsecaseAuction_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Auction, int, error)) *MockUsecaseAuction_Get_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceBid provides a mock function with given fields: ctx, in
func (_m *MockUsecaseAuction) PlaceBid(ctx context.Context, in biz.PlaceBidInput) (entity.PassiveBid, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PlaceBid")
	}

	var r0 entity.PassiveBid
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.PlaceBidInput) (entity.PassiveBid, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.PlaceBidInput) entity.PassiveBid); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(entity.PassiveBid)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.PlaceBidInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseAuction_PlaceBid_Call struct {
	*mock.Call
}

func (_e *MockUsecaseAuction_Expecter) PlaceBid(ctx interface{}, in interface{}) *MockUsecaseAuction_PlaceBid_Call {
	return &MockUsecaseAuction_PlaceBid_Call{Call: _e.mock.On("PlaceBid", ctx, in)}
}

func (_c *MockUsecaseAuction_PlaceBid_Call) Run(run func(ctx context.Context, in biz.PlaceBidInput)) *MockUsecaseAuction_PlaceBid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.PlaceBidInput))
	})
	return _c
}

func (_c *MockUsecaseAuction_PlaceBid_Call) Return(_a0 entity.PassiveBid, _a1 error) *MockUsecaseAuction_PlaceBid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuction_PlaceBid_Call) RunAndReturn(run func(context.Context, biz.PlaceBidInput) (entity.PassiveBid, error)) *MockUsecaseAuction_PlaceBid_Call {
	_c.Call.Return(run)
	return _c
}

// Standing provides a mock function with given fields: ctx, auctionID, bidderID
func (_m *MockUsecaseAuction) Standing(ctx context.Context, auctionID uuid.UUID, bidderID uuid.UUID) (biz.Standing, error) {
	ret := _m.Called(ctx, auctionID, bidderID)

	if len(ret) == 0 {
		panic("no return value specified for Standing")
	}

	var r0 biz.Standing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (biz.Standing, error)); ok {
		return rf(ctx, auctionID, bidderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) biz.Standing); ok {
		r0 = rf(ctx, auctionID, bidderID)
	} else {
		r0 = ret.Get(0).(biz.Standing)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, auctionID, bidderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseAuction_Standing_Call struct {
	*mock.Call
}

func (_e *MockUsecaseAuction_Expecter) Standing(ctx interface{}, auctionID interface{}, bidderID interface{}) *MockUsecaseAuction_Standing_Call {
	return &MockUsecaseAuction_Standing_Call{Call: _e.mock.On("Standing", ctx, auctionID, bidderID)}
}

func (_c *MockUsecaseAuction_Standing_Call) Run(run func(ctx context.Context, auctionID uuid.UUID, bidderID uuid.UUID)) *MockUsecaseAuction_Standing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAuction_Standing_Call) Return(_a0 biz.Standing, _a1 error) *MockUsecaseAuction_Standing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuction_Standing_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (biz.Standing, error)) *MockUsecaseAuction_Standing_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx, auctionID
func (_m *MockUsecaseAuction) Close(ctx context.Context, auctionID uuid.UUID) (entity.Auction, error) {
	ret := _m.Called(ctx, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 entity.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Auction, error)); ok {
		return rf(ctx, auctionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Auction); ok {
		r0 = rf(ctx, auctionID)
	} else {
		r0 = ret.Get(0).(entity.Auction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseAuction_Close_Call struct {
	*mock.Call
}

func (_e *MockUsecaseAuction_Expecter) Close(ctx interface{}, auctionID interface{}) *MockUsecaseAuction_Close_Call {
	return &MockUsecaseAuction_Close_Call{Call: _e.mock.On("Close", ctx, auctionID)}
}

func (_c *MockUsecaseAuction_Close_Call) Run(run func(ctx context.Context, auctionID uuid.UUID)) *MockUsecaseAuction_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAuction_Close_Call) Return(_a0 entity.Auction, _a1 error) *MockUsecaseAuction_Close_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuction_Close_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Auction, error)) *MockUsecaseAuction_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFromLotScheduled provides a mock function with given fields: ctx, in, idempotencyKey
func (_m *MockUsecaseAuction) CreateFromLotScheduled(ctx context.Context, in biz.LotScheduledInput, idempotencyKey string) error {
	ret := _m.Called(ctx, in, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromLotScheduled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.LotScheduledInput, string) error); ok {
		r0 = rf(ctx, in, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockUsecaseAuction_CreateFromLotScheduled_Call struct {
	*mock.Call
}

func (_e *MockUsecaseAuction_Expecter) CreateFromLotScheduled(ctx interface{}, in interface{}, idempotencyKey interface{}) *MockUsecaseAuction_CreateFromLotScheduled_Call {
	return &MockUsecaseAuction_CreateFromLotScheduled_Call{Call: _e.mock.On("CreateFromLotScheduled", ctx, in, idempotencyKey)}
}

func (_c *MockUsecaseAuction_CreateFromLotScheduled_Call) Run(run func(ctx context.Context, in biz.LotScheduledInput, idempotencyKey string)) *MockUsecaseAuction_CreateFromLotScheduled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.LotScheduledInput), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseAuction_CreateFromLotScheduled_Call) Return(_a0 error) *MockUsecaseAuction_CreateFromLotScheduled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseAuction_CreateFromLotScheduled_Call) RunAndReturn(run func(context.Context, biz.LotScheduledInput, string) error) *MockUsecaseAuction_CreateFromLotScheduled_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseAuction creates a new instance of MockUsecaseAuction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseAuction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseAuction {
	mock := &MockUsecaseAuction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
