// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://aban.io/support",
            "email": "info@aban.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apis/admin/invites": {
            "get": {
                "description": "List/filter invites for the admin console.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invites Admin"
                ],
                "summary": "List invites (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (ISSUED|REDEEMED|REVOKED|FLAGGED)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by issuer account id",
                        "name": "issuer",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.InviteListResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/apis/admin/invites/chain/{accountId}": {
            "get": {
                "description": "List the invitees an account brought in (invite_edge where it is the inviter).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invites Admin"
                ],
                "summary": "Invite chain (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Inviter account id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.InviteChainResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/apis/admin/invites/{code}/flag": {
            "post": {
                "description": "Move an ISSUED code to FLAGGED. Non-ISSUED -\u003e 400.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invites Admin"
                ],
                "summary": "Flag an invite (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invite code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Not in ISSUED state",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/apis/admin/invites/{code}/revoke": {
            "post": {
                "description": "Move an ISSUED code to REVOKED. Non-ISSUED -\u003e 400.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invites Admin"
                ],
                "summary": "Revoke an invite (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invite code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Not in ISSUED state",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/apis/invites": {
            "post": {
                "description": "A MEMBER/VIP issues a new single-use invite code (subject to the per-issuer quota).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invites"
                ],
                "summary": "Issue an invite code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authenticated account id (gateway-injected)",
                        "name": "X-Account-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.IssueInviteResp"
                        }
                    },
                    "400": {
                        "description": "Quota exceeded / invalid",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/apis/invites/redeem": {
            "post": {
                "description": "Atomically consume a single-use invite code, elevating the caller. Emits invite.redeemed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invites"
                ],
                "summary": "Redeem an invite code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authenticated account id (gateway-injected)",
                        "name": "X-Account-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Invite code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RedeemInviteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RedeemInviteResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request / not redeemable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz/liveness": {
            "get": {
                "description": "Check the liveness of the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthz"
                ],
                "summary": "Healthz Liveness",
                "operationId": "healthz-liveness",
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/healthz/panic": {
            "get": {
                "tags": [
                    "healthz"
                ],
                "summary": "Panic for test",
                "responses": {
                    "500": {
                        "description": "panic",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz/rediness": {
            "get": {
                "description": "Check the readiness of the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthz"
                ],
                "summary": "Healthz Readiness",
                "operationId": "healthz-rediness",
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/healthz/sleep/{time}": {
            "get": {
                "tags": [
                    "healthz"
                ],
                "summary": "Long Run for test",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Time to sleep, e.g. 30s",
                        "name": "time",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.InviteChainResp": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.InviteEdgeResp"
                    }
                }
            }
        },
        "dto.InviteEdgeResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "inviteeAccountId": {
                    "type": "string"
                },
                "inviterAccountId": {
                    "type": "string"
                }
            }
        },
        "dto.InviteListResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "invites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.InviteResp"
                    }
                }
            }
        },
        "dto.InviteResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "issuerAccountId": {
                    "type": "string"
                },
                "redeemedAt": {
                    "type": "string"
                },
                "redeemedBy": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.IssueInviteResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "issuerAccountId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.RedeemInviteReq": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 4
                }
            }
        },
        "dto.RedeemInviteResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "issuedBy": {
                    "type": "string"
                },
                "redeemedBy": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger",
	Description:      "API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
