// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	biz "application/internal/biz"
	entity "application/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockUsecaseAccess is an autogenerated mock type for the UsecaseAccess type
type MockUsecaseAccess struct {
	mock.Mock
}

type MockUsecaseAccess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseAccess) EXPECT() *MockUsecaseAccess_Expecter {
	return &MockUsecaseAccess_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, accountID, req
func (_m *MockUsecaseAccess) Authorize(ctx context.Context, accountID string, req biz.RouteRequirement) (biz.GuardResult, error) {
	ret := _m.Called(ctx, accountID, req)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 biz.GuardResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, biz.RouteRequirement) (biz.GuardResult, error)); ok {
		return rf(ctx, accountID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, biz.RouteRequirement) biz.GuardResult); ok {
		r0 = rf(ctx, accountID, req)
	} else {
		r0 = ret.Get(0).(biz.GuardResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, biz.RouteRequirement) error); ok {
		r1 = rf(ctx, accountID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseAccess_Authorize_Call struct {
	*mock.Call
}

func (_e *MockUsecaseAccess_Expecter) Authorize(ctx interface{}, accountID interface{}, req interface{}) *MockUsecaseAccess_Authorize_Call {
	return &MockUsecaseAccess_Authorize_Call{Call: _e.mock.On("Authorize", ctx, accountID, req)}
}

func (_c *MockUsecaseAccess_Authorize_Call) Run(run func(ctx context.Context, accountID string, req biz.RouteRequirement)) *MockUsecaseAccess_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(biz.RouteRequirement))
	})
	return _c
}

func (_c *MockUsecaseAccess_Authorize_Call) Return(_a0 biz.GuardResult, _a1 error) *MockUsecaseAccess_Authorize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccess_Authorize_Call) RunAndReturn(run func(context.Context, string, biz.RouteRequirement) (biz.GuardResult, error)) *MockUsecaseAccess_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// Lookup provides a mock function with given fields: ctx, accountID
func (_m *MockUsecaseAccess) Lookup(ctx context.Context, accountID string) (entity.Access, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 entity.Access
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Access, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Access); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(entity.Access)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseAccess_Lookup_Call struct {
	*mock.Call
}

func (_e *MockUsecaseAccess_Expecter) Lookup(ctx interface{}, accountID interface{}) *MockUsecaseAccess_Lookup_Call {
	return &MockUsecaseAccess_Lookup_Call{Call: _e.mock.On("Lookup", ctx, accountID)}
}

func (_c *MockUsecaseAccess_Lookup_Call) Run(run func(ctx context.Context, accountID string)) *MockUsecaseAccess_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsecaseAccess_Lookup_Call) Return(_a0 entity.Access, _a1 error) *MockUsecaseAccess_Lookup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccess_Lookup_Call) RunAndReturn(run func(context.Context, string) (entity.Access, error)) *MockUsecaseAccess_Lookup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseAccess creates a new instance of MockUsecaseAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseAccess {
	mock := &MockUsecaseAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
