// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	context "context"

	entity "application/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryInvite is an autogenerated mock type for the RepositoryInvite type
type MockRepositoryInvite struct {
	mock.Mock
}

type MockRepositoryInvite_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryInvite) EXPECT() *MockRepositoryInvite_Expecter {
	return &MockRepositoryInvite_Expecter{mock: &_m.Mock}
}

// Chain provides a mock function with given fields: ctx, accountID
func (_m *MockRepositoryInvite) Chain(ctx context.Context, accountID string) ([]entity.InviteEdge, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Chain")
	}

	var r0 []entity.InviteEdge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.InviteEdge, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.InviteEdge); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.InviteEdge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryInvite_Chain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chain'
type MockRepositoryInvite_Chain_Call struct {
	*mock.Call
}

// Chain is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockRepositoryInvite_Expecter) Chain(ctx interface{}, accountID interface{}) *MockRepositoryInvite_Chain_Call {
	return &MockRepositoryInvite_Chain_Call{Call: _e.mock.On("Chain", ctx, accountID)}
}

func (_c *MockRepositoryInvite_Chain_Call) Run(run func(ctx context.Context, accountID string)) *MockRepositoryInvite_Chain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryInvite_Chain_Call) Return(_a0 []entity.InviteEdge, _a1 error) *MockRepositoryInvite_Chain_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryInvite_Chain_Call) RunAndReturn(run func(context.Context, string) ([]entity.InviteEdge, error)) *MockRepositoryInvite_Chain_Call {
	_c.Call.Return(run)
	return _c
}

// CountByIssuer provides a mock function with given fields: ctx, issuerAccountID
func (_m *MockRepositoryInvite) CountByIssuer(ctx context.Context, issuerAccountID string) (int, error) {
	ret := _m.Called(ctx, issuerAccountID)

	if len(ret) == 0 {
		panic("no return value specified for CountByIssuer")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, issuerAccountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, issuerAccountID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, issuerAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryInvite_CountByIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByIssuer'
type MockRepositoryInvite_CountByIssuer_Call struct {
	*mock.Call
}

// CountByIssuer is a helper method to define mock.On call
//   - ctx context.Context
//   - issuerAccountID string
func (_e *MockRepositoryInvite_Expecter) CountByIssuer(ctx interface{}, issuerAccountID interface{}) *MockRepositoryInvite_CountByIssuer_Call {
	return &MockRepositoryInvite_CountByIssuer_Call{Call: _e.mock.On("CountByIssuer", ctx, issuerAccountID)}
}

func (_c *MockRepositoryInvite_CountByIssuer_Call) Run(run func(ctx context.Context, issuerAccountID string)) *MockRepositoryInvite_CountByIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryInvite_CountByIssuer_Call) Return(_a0 int, _a1 error) *MockRepositoryInvite_CountByIssuer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryInvite_CountByIssuer_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockRepositoryInvite_CountByIssuer_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, inv
func (_m *MockRepositoryInvite) Create(ctx context.Context, inv entity.Invite) (entity.Invite, error) {
	ret := _m.Called(ctx, inv)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Invite) (entity.Invite, error)); ok {
		return rf(ctx, inv)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Invite) entity.Invite); ok {
		r0 = rf(ctx, inv)
	} else {
		r0 = ret.Get(0).(entity.Invite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Invite) error); ok {
		r1 = rf(ctx, inv)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryInvite_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepositoryInvite_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - inv entity.Invite
func (_e *MockRepositoryInvite_Expecter) Create(ctx interface{}, inv interface{}) *MockRepositoryInvite_Create_Call {
	return &MockRepositoryInvite_Create_Call{Call: _e.mock.On("Create", ctx, inv)}
}

func (_c *MockRepositoryInvite_Create_Call) Run(run func(ctx context.Context, inv entity.Invite)) *MockRepositoryInvite_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Invite))
	})
	return _c
}

func (_c *MockRepositoryInvite_Create_Call) Return(_a0 entity.Invite, _a1 error) *MockRepositoryInvite_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryInvite_Create_Call) RunAndReturn(run func(context.Context, entity.Invite) (entity.Invite, error)) *MockRepositoryInvite_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, f
func (_m *MockRepositoryInvite) List(ctx context.Context, f biz.ListInvitesFilter) ([]entity.Invite, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListInvitesFilter) ([]entity.Invite, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListInvitesFilter) []entity.Invite); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.ListInvitesFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryInvite_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepositoryInvite_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - f biz.ListInvitesFilter
func (_e *MockRepositoryInvite_Expecter) List(ctx interface{}, f interface{}) *MockRepositoryInvite_List_Call {
	return &MockRepositoryInvite_List_Call{Call: _e.mock.On("List", ctx, f)}
}

func (_c *MockRepositoryInvite_List_Call) Run(run func(ctx context.Context, f biz.ListInvitesFilter)) *MockRepositoryInvite_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.ListInvitesFilter))
	})
	return _c
}

func (_c *MockRepositoryInvite_List_Call) Return(_a0 []entity.Invite, _a1 error) *MockRepositoryInvite_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryInvite_List_Call) RunAndReturn(run func(context.Context, biz.ListInvitesFilter) ([]entity.Invite, error)) *MockRepositoryInvite_List_Call {
	_c.Call.Return(run)
	return _c
}

// Redeem provides a mock function with given fields: ctx, code, redeemerAccountID, outboxPayload, idempotencyKey
func (_m *MockRepositoryInvite) Redeem(ctx context.Context, code string, redeemerAccountID string, outboxPayload string, idempotencyKey string) (biz.RedeemResult, error) {
	ret := _m.Called(ctx, code, redeemerAccountID, outboxPayload, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Redeem")
	}

	var r0 biz.RedeemResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (biz.RedeemResult, error)); ok {
		return rf(ctx, code, redeemerAccountID, outboxPayload, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) biz.RedeemResult); ok {
		r0 = rf(ctx, code, redeemerAccountID, outboxPayload, idempotencyKey)
	} else {
		r0 = ret.Get(0).(biz.RedeemResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, code, redeemerAccountID, outboxPayload, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryInvite_Redeem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redeem'
type MockRepositoryInvite_Redeem_Call struct {
	*mock.Call
}

// Redeem is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - redeemerAccountID string
//   - outboxPayload string
//   - idempotencyKey string
func (_e *MockRepositoryInvite_Expecter) Redeem(ctx interface{}, code interface{}, redeemerAccountID interface{}, outboxPayload interface{}, idempotencyKey interface{}) *MockRepositoryInvite_Redeem_Call {
	return &MockRepositoryInvite_Redeem_Call{Call: _e.mock.On("Redeem", ctx, code, redeemerAccountID, outboxPayload, idempotencyKey)}
}

func (_c *MockRepositoryInvite_Redeem_Call) Run(run func(ctx context.Context, code string, redeemerAccountID string, outboxPayload string, idempotencyKey string)) *MockRepositoryInvite_Redeem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockRepositoryInvite_Redeem_Call) Return(_a0 biz.RedeemResult, _a1 error) *MockRepositoryInvite_Redeem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryInvite_Redeem_Call) RunAndReturn(run func(context.Context, string, string, string, string) (biz.RedeemResult, error)) *MockRepositoryInvite_Redeem_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function with given fields: ctx, code, target
func (_m *MockRepositoryInvite) SetStatus(ctx context.Context, code string, target entity.InviteStatus) error {
	ret := _m.Called(ctx, code, target)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.InviteStatus) error); ok {
		r0 = rf(ctx, code, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryInvite_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockRepositoryInvite_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - target entity.InviteStatus
func (_e *MockRepositoryInvite_Expecter) SetStatus(ctx interface{}, code interface{}, target interface{}) *MockRepositoryInvite_SetStatus_Call {
	return &MockRepositoryInvite_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, code, target)}
}

func (_c *MockRepositoryInvite_SetStatus_Call) Run(run func(ctx context.Context, code string, target entity.InviteStatus)) *MockRepositoryInvite_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.InviteStatus))
	})
	return _c
}

func (_c *MockRepositoryInvite_SetStatus_Call) Return(_a0 error) *MockRepositoryInvite_SetStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryInvite_SetStatus_Call) RunAndReturn(run func(context.Context, string, entity.InviteStatus) error) *MockRepositoryInvite_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryInvite creates a new instance of MockRepositoryInvite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryInvite(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryInvite {
	mock := &MockRepositoryInvite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
