// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	context "context"

	entity "application/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockUsecaseInvite is an autogenerated mock type for the UsecaseInvite type
type MockUsecaseInvite struct {
	mock.Mock
}

type MockUsecaseInvite_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseInvite) EXPECT() *MockUsecaseInvite_Expecter {
	return &MockUsecaseInvite_Expecter{mock: &_m.Mock}
}

// Chain provides a mock function with given fields: ctx, accountID
func (_m *MockUsecaseInvite) Chain(ctx context.Context, accountID string) ([]entity.InviteEdge, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Chain")
	}

	var r0 []entity.InviteEdge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.InviteEdge, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.InviteEdge); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.InviteEdge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseInvite_Chain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chain'
type MockUsecaseInvite_Chain_Call struct {
	*mock.Call
}

// Chain is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockUsecaseInvite_Expecter) Chain(ctx interface{}, accountID interface{}) *MockUsecaseInvite_Chain_Call {
	return &MockUsecaseInvite_Chain_Call{Call: _e.mock.On("Chain", ctx, accountID)}
}

func (_c *MockUsecaseInvite_Chain_Call) Run(run func(ctx context.Context, accountID string)) *MockUsecaseInvite_Chain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsecaseInvite_Chain_Call) Return(_a0 []entity.InviteEdge, _a1 error) *MockUsecaseInvite_Chain_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseInvite_Chain_Call) RunAndReturn(run func(context.Context, string) ([]entity.InviteEdge, error)) *MockUsecaseInvite_Chain_Call {
	_c.Call.Return(run)
	return _c
}

// Flag provides a mock function with given fields: ctx, code
func (_m *MockUsecaseInvite) Flag(ctx context.Context, code string) error {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Flag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseInvite_Flag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flag'
type MockUsecaseInvite_Flag_Call struct {
	*mock.Call
}

// Flag is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockUsecaseInvite_Expecter) Flag(ctx interface{}, code interface{}) *MockUsecaseInvite_Flag_Call {
	return &MockUsecaseInvite_Flag_Call{Call: _e.mock.On("Flag", ctx, code)}
}

func (_c *MockUsecaseInvite_Flag_Call) Run(run func(ctx context.Context, code string)) *MockUsecaseInvite_Flag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsecaseInvite_Flag_Call) Return(_a0 error) *MockUsecaseInvite_Flag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseInvite_Flag_Call) RunAndReturn(run func(context.Context, string) error) *MockUsecaseInvite_Flag_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function with given fields: ctx, issuerAccountID
func (_m *MockUsecaseInvite) Issue(ctx context.Context, issuerAccountID string) (entity.Invite, error) {
	ret := _m.Called(ctx, issuerAccountID)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 entity.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Invite, error)); ok {
		return rf(ctx, issuerAccountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Invite); ok {
		r0 = rf(ctx, issuerAccountID)
	} else {
		r0 = ret.Get(0).(entity.Invite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, issuerAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseInvite_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockUsecaseInvite_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - issuerAccountID string
func (_e *MockUsecaseInvite_Expecter) Issue(ctx interface{}, issuerAccountID interface{}) *MockUsecaseInvite_Issue_Call {
	return &MockUsecaseInvite_Issue_Call{Call: _e.mock.On("Issue", ctx, issuerAccountID)}
}

func (_c *MockUsecaseInvite_Issue_Call) Run(run func(ctx context.Context, issuerAccountID string)) *MockUsecaseInvite_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsecaseInvite_Issue_Call) Return(_a0 entity.Invite, _a1 error) *MockUsecaseInvite_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseInvite_Issue_Call) RunAndReturn(run func(context.Context, string) (entity.Invite, error)) *MockUsecaseInvite_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, f
func (_m *MockUsecaseInvite) List(ctx context.Context, f biz.ListInvitesFilter) ([]entity.Invite, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListInvitesFilter) ([]entity.Invite, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListInvitesFilter) []entity.Invite); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.ListInvitesFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseInvite_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUsecaseInvite_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - f biz.ListInvitesFilter
func (_e *MockUsecaseInvite_Expecter) List(ctx interface{}, f interface{}) *MockUsecaseInvite_List_Call {
	return &MockUsecaseInvite_List_Call{Call: _e.mock.On("List", ctx, f)}
}

func (_c *MockUsecaseInvite_List_Call) Run(run func(ctx context.Context, f biz.ListInvitesFilter)) *MockUsecaseInvite_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.ListInvitesFilter))
	})
	return _c
}

func (_c *MockUsecaseInvite_List_Call) Return(_a0 []entity.Invite, _a1 error) *MockUsecaseInvite_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseInvite_List_Call) RunAndReturn(run func(context.Context, biz.ListInvitesFilter) ([]entity.Invite, error)) *MockUsecaseInvite_List_Call {
	_c.Call.Return(run)
	return _c
}

// Redeem provides a mock function with given fields: ctx, code, redeemerAccountID
func (_m *MockUsecaseInvite) Redeem(ctx context.Context, code string, redeemerAccountID string) (biz.RedeemResult, error) {
	ret := _m.Called(ctx, code, redeemerAccountID)

	if len(ret) == 0 {
		panic("no return value specified for Redeem")
	}

	var r0 biz.RedeemResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (biz.RedeemResult, error)); ok {
		return rf(ctx, code, redeemerAccountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) biz.RedeemResult); ok {
		r0 = rf(ctx, code, redeemerAccountID)
	} else {
		r0 = ret.Get(0).(biz.RedeemResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, code, redeemerAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseInvite_Redeem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redeem'
type MockUsecaseInvite_Redeem_Call struct {
	*mock.Call
}

// Redeem is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - redeemerAccountID string
func (_e *MockUsecaseInvite_Expecter) Redeem(ctx interface{}, code interface{}, redeemerAccountID interface{}) *MockUsecaseInvite_Redeem_Call {
	return &MockUsecaseInvite_Redeem_Call{Call: _e.mock.On("Redeem", ctx, code, redeemerAccountID)}
}

func (_c *MockUsecaseInvite_Redeem_Call) Run(run func(ctx context.Context, code string, redeemerAccountID string)) *MockUsecaseInvite_Redeem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseInvite_Redeem_Call) Return(_a0 biz.RedeemResult, _a1 error) *MockUsecaseInvite_Redeem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseInvite_Redeem_Call) RunAndReturn(run func(context.Context, string, string) (biz.RedeemResult, error)) *MockUsecaseInvite_Redeem_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, code
func (_m *MockUsecaseInvite) Revoke(ctx context.Context, code string) error {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseInvite_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockUsecaseInvite_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockUsecaseInvite_Expecter) Revoke(ctx interface{}, code interface{}) *MockUsecaseInvite_Revoke_Call {
	return &MockUsecaseInvite_Revoke_Call{Call: _e.mock.On("Revoke", ctx, code)}
}

func (_c *MockUsecaseInvite_Revoke_Call) Run(run func(ctx context.Context, code string)) *MockUsecaseInvite_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsecaseInvite_Revoke_Call) Return(_a0 error) *MockUsecaseInvite_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseInvite_Revoke_Call) RunAndReturn(run func(context.Context, string) error) *MockUsecaseInvite_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseInvite creates a new instance of MockUsecaseInvite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseInvite(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseInvite {
	mock := &MockUsecaseInvite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
