// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseDispute is an autogenerated mock type for the UsecaseDispute type
type MockUsecaseDispute struct {
	mock.Mock
}

type MockUsecaseDispute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseDispute) EXPECT() *MockUsecaseDispute_Expecter {
	return &MockUsecaseDispute_Expecter{mock: &_m.Mock}
}

// AddEvidence provides a mock function with given fields: ctx, tradeID, caller, detailRef
func (_m *MockUsecaseDispute) AddEvidence(ctx context.Context, tradeID string, caller uuid.UUID, detailRef string) error {
	ret := _m.Called(ctx, tradeID, caller, detailRef)

	if len(ret) == 0 {
		panic("no return value specified for AddEvidence")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string) error); ok {
		r0 = rf(ctx, tradeID, caller, detailRef)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseDispute_AddEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEvidence'
type MockUsecaseDispute_AddEvidence_Call struct {
	*mock.Call
}

// AddEvidence is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID string
//   - caller uuid.UUID
//   - detailRef string
func (_e *MockUsecaseDispute_Expecter) AddEvidence(ctx interface{}, tradeID interface{}, caller interface{}, detailRef interface{}) *MockUsecaseDispute_AddEvidence_Call {
	return &MockUsecaseDispute_AddEvidence_Call{Call: _e.mock.On("AddEvidence", ctx, tradeID, caller, detailRef)}
}

func (_c *MockUsecaseDispute_AddEvidence_Call) Run(run func(ctx context.Context, tradeID string, caller uuid.UUID, detailRef string)) *MockUsecaseDispute_AddEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockUsecaseDispute_AddEvidence_Call) Return(_a0 error) *MockUsecaseDispute_AddEvidence_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseDispute_AddEvidence_Call) RunAndReturn(run func(context.Context, string, uuid.UUID, string) error) *MockUsecaseDispute_AddEvidence_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, tradeID, caller, admin
func (_m *MockUsecaseDispute) Get(ctx context.Context, tradeID string, caller uuid.UUID, admin bool) (biz.DisputeView, error) {
	ret := _m.Called(ctx, tradeID, caller, admin)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 biz.DisputeView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, bool) (biz.DisputeView, error)); ok {
		return rf(ctx, tradeID, caller, admin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, bool) biz.DisputeView); ok {
		r0 = rf(ctx, tradeID, caller, admin)
	} else {
		r0 = ret.Get(0).(biz.DisputeView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, tradeID, caller, admin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDispute_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecaseDispute_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID string
//   - caller uuid.UUID
//   - admin bool
func (_e *MockUsecaseDispute_Expecter) Get(ctx interface{}, tradeID interface{}, caller interface{}, admin interface{}) *MockUsecaseDispute_Get_Call {
	return &MockUsecaseDispute_Get_Call{Call: _e.mock.On("Get", ctx, tradeID, caller, admin)}
}

func (_c *MockUsecaseDispute_Get_Call) Run(run func(ctx context.Context, tradeID string, caller uuid.UUID, admin bool)) *MockUsecaseDispute_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *MockUsecaseDispute_Get_Call) Return(_a0 biz.DisputeView, _a1 error) *MockUsecaseDispute_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDispute_Get_Call) RunAndReturn(run func(context.Context, string, uuid.UUID, bool) (biz.DisputeView, error)) *MockUsecaseDispute_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByState provides a mock function with given fields: ctx, f
func (_m *MockUsecaseDispute) ListByState(ctx context.Context, f biz.ListFilter) ([]entity.Dispute, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for ListByState")
	}

	var r0 []entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListFilter) ([]entity.Dispute, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.ListFilter) []entity.Dispute); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Dispute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.ListFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDispute_ListByState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByState'
type MockUsecaseDispute_ListByState_Call struct {
	*mock.Call
}

// ListByState is a helper method to define mock.On call
//   - ctx context.Context
//   - f biz.ListFilter
func (_e *MockUsecaseDispute_Expecter) ListByState(ctx interface{}, f interface{}) *MockUsecaseDispute_ListByState_Call {
	return &MockUsecaseDispute_ListByState_Call{Call: _e.mock.On("ListByState", ctx, f)}
}

func (_c *MockUsecaseDispute_ListByState_Call) Run(run func(ctx context.Context, f biz.ListFilter)) *MockUsecaseDispute_ListByState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.ListFilter))
	})
	return _c
}

func (_c *MockUsecaseDispute_ListByState_Call) Return(_a0 []entity.Dispute, _a1 error) *MockUsecaseDispute_ListByState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDispute_ListByState_Call) RunAndReturn(run func(context.Context, biz.ListFilter) ([]entity.Dispute, error)) *MockUsecaseDispute_ListByState_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with given fields: ctx, p
func (_m *MockUsecaseDispute) Open(ctx context.Context, p biz.OpenParams) (entity.Dispute, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.OpenParams) (entity.Dispute, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.OpenParams) entity.Dispute); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(entity.Dispute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.OpenParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDispute_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockUsecaseDispute_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - p biz.OpenParams
func (_e *MockUsecaseDispute_Expecter) Open(ctx interface{}, p interface{}) *MockUsecaseDispute_Open_Call {
	return &MockUsecaseDispute_Open_Call{Call: _e.mock.On("Open", ctx, p)}
}

func (_c *MockUsecaseDispute_Open_Call) Run(run func(ctx context.Context, p biz.OpenParams)) *MockUsecaseDispute_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.OpenParams))
	})
	return _c
}

func (_c *MockUsecaseDispute_Open_Call) Return(_a0 entity.Dispute, _a1 error) *MockUsecaseDispute_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDispute_Open_Call) RunAndReturn(run func(context.Context, biz.OpenParams) (entity.Dispute, error)) *MockUsecaseDispute_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: ctx, tradeID, ruling, ruledBy
func (_m *MockUsecaseDispute) Resolve(ctx context.Context, tradeID string, ruling entity.Ruling, ruledBy uuid.UUID) (entity.Dispute, error) {
	ret := _m.Called(ctx, tradeID, ruling, ruledBy)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Ruling, uuid.UUID) (entity.Dispute, error)); ok {
		return rf(ctx, tradeID, ruling, ruledBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Ruling, uuid.UUID) entity.Dispute); ok {
		r0 = rf(ctx, tradeID, ruling, ruledBy)
	} else {
		r0 = ret.Get(0).(entity.Dispute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.Ruling, uuid.UUID) error); ok {
		r1 = rf(ctx, tradeID, ruling, ruledBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDispute_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockUsecaseDispute_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID string
//   - ruling entity.Ruling
//   - ruledBy uuid.UUID
func (_e *MockUsecaseDispute_Expecter) Resolve(ctx interface{}, tradeID interface{}, ruling interface{}, ruledBy interface{}) *MockUsecaseDispute_Resolve_Call {
	return &MockUsecaseDispute_Resolve_Call{Call: _e.mock.On("Resolve", ctx, tradeID, ruling, ruledBy)}
}

func (_c *MockUsecaseDispute_Resolve_Call) Run(run func(ctx context.Context, tradeID string, ruling entity.Ruling, ruledBy uuid.UUID)) *MockUsecaseDispute_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.Ruling), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseDispute_Resolve_Call) Return(_a0 entity.Dispute, _a1 error) *MockUsecaseDispute_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDispute_Resolve_Call) RunAndReturn(run func(context.Context, string, entity.Ruling, uuid.UUID) (entity.Dispute, error)) *MockUsecaseDispute_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// StartReview provides a mock function with given fields: ctx, disputeID, admin
func (_m *MockUsecaseDispute) StartReview(ctx context.Context, disputeID uuid.UUID, admin uuid.UUID) (entity.Dispute, error) {
	ret := _m.Called(ctx, disputeID, admin)

	if len(ret) == 0 {
		panic("no return value specified for StartReview")
	}

	var r0 entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (entity.Dispute, error)); ok {
		return rf(ctx, disputeID, admin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) entity.Dispute); ok {
		r0 = rf(ctx, disputeID, admin)
	} else {
		r0 = ret.Get(0).(entity.Dispute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, disputeID, admin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDispute_StartReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartReview'
type MockUsecaseDispute_StartReview_Call struct {
	*mock.Call
}

// StartReview is a helper method to define mock.On call
//   - ctx context.Context
//   - disputeID uuid.UUID
//   - admin uuid.UUID
func (_e *MockUsecaseDispute_Expecter) StartReview(ctx interface{}, disputeID interface{}, admin interface{}) *MockUsecaseDispute_StartReview_Call {
	return &MockUsecaseDispute_StartReview_Call{Call: _e.mock.On("StartReview", ctx, disputeID, admin)}
}

func (_c *MockUsecaseDispute_StartReview_Call) Run(run func(ctx context.Context, disputeID uuid.UUID, admin uuid.UUID)) *MockUsecaseDispute_StartReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseDispute_StartReview_Call) Return(_a0 entity.Dispute, _a1 error) *MockUsecaseDispute_StartReview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDispute_StartReview_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (entity.Dispute, error)) *MockUsecaseDispute_StartReview_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, tradeID, caller
func (_m *MockUsecaseDispute) Withdraw(ctx context.Context, tradeID string, caller uuid.UUID) (entity.Dispute, error) {
	ret := _m.Called(ctx, tradeID, caller)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (entity.Dispute, error)); ok {
		return rf(ctx, tradeID, caller)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) entity.Dispute); ok {
		r0 = rf(ctx, tradeID, caller)
	} else {
		r0 = ret.Get(0).(entity.Dispute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, tradeID, caller)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseDispute_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockUsecaseDispute_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID string
//   - caller uuid.UUID
func (_e *MockUsecaseDispute_Expecter) Withdraw(ctx interface{}, tradeID interface{}, caller interface{}) *MockUsecaseDispute_Withdraw_Call {
	return &MockUsecaseDispute_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, tradeID, caller)}
}

func (_c *MockUsecaseDispute_Withdraw_Call) Run(run func(ctx context.Context, tradeID string, caller uuid.UUID)) *MockUsecaseDispute_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseDispute_Withdraw_Call) Return(_a0 entity.Dispute, _a1 error) *MockUsecaseDispute_Withdraw_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseDispute_Withdraw_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) (entity.Dispute, error)) *MockUsecaseDispute_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseDispute creates a new instance of MockUsecaseDispute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseDispute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseDispute {
	mock := &MockUsecaseDispute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
