// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryDispute is an autogenerated mock type for the RepositoryDispute type
type MockRepositoryDispute struct {
	mock.Mock
}

type MockRepositoryDispute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryDispute) EXPECT() *MockRepositoryDispute_Expecter {
	return &MockRepositoryDispute_Expecter{mock: &_m.Mock}
}

// AppendEvent provides a mock function with given fields: ctx, audit
func (_m *MockRepositoryDispute) AppendEvent(ctx context.Context, audit entity.DisputeEvent) error {
	ret := _m.Called(ctx, audit)

	if len(ret) == 0 {
		panic("no return value specified for AppendEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.DisputeEvent) error); ok {
		r0 = rf(ctx, audit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryDispute_AppendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEvent'
type MockRepositoryDispute_AppendEvent_Call struct {
	*mock.Call
}

// AppendEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - audit entity.DisputeEvent
func (_e *MockRepositoryDispute_Expecter) AppendEvent(ctx interface{}, audit interface{}) *MockRepositoryDispute_AppendEvent_Call {
	return &MockRepositoryDispute_AppendEvent_Call{Call: _e.mock.On("AppendEvent", ctx, audit)}
}

func (_c *MockRepositoryDispute_AppendEvent_Call) Run(run func(ctx context.Context, audit entity.DisputeEvent)) *MockRepositoryDispute_AppendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.DisputeEvent))
	})
	return _c
}

func (_c *MockRepositoryDispute_AppendEvent_Call) Return(_a0 error) *MockRepositoryDispute_AppendEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryDispute_AppendEvent_Call) RunAndReturn(run func(context.Context, entity.DisputeEvent) error) *MockRepositoryDispute_AppendEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTx provides a mock function with given fields: ctx, d, audit, outbox
func (_m *MockRepositoryDispute) CreateTx(ctx context.Context, d entity.Dispute, audit entity.DisputeEvent, outbox entity.OutboxEvent) (entity.Dispute, error) {
	ret := _m.Called(ctx, d, audit, outbox)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Dispute, entity.DisputeEvent, entity.OutboxEvent) (entity.Dispute, error)); ok {
		return rf(ctx, d, audit, outbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Dispute, entity.DisputeEvent, entity.OutboxEvent) entity.Dispute); ok {
		r0 = rf(ctx, d, audit, outbox)
	} else {
		r0 = ret.Get(0).(entity.Dispute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Dispute, entity.DisputeEvent, entity.OutboxEvent) error); ok {
		r1 = rf(ctx, d, audit, outbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryDispute_CreateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTx'
type MockRepositoryDispute_CreateTx_Call struct {
	*mock.Call
}

// CreateTx is a helper method to define mock.On call
//   - ctx context.Context
//   - d entity.Dispute
//   - audit entity.DisputeEvent
//   - outbox entity.OutboxEvent
func (_e *MockRepositoryDispute_Expecter) CreateTx(ctx interface{}, d interface{}, audit interface{}, outbox interface{}) *MockRepositoryDispute_CreateTx_Call {
	return &MockRepositoryDispute_CreateTx_Call{Call: _e.mock.On("CreateTx", ctx, d, audit, outbox)}
}

func (_c *MockRepositoryDispute_CreateTx_Call) Run(run func(ctx context.Context, d entity.Dispute, audit entity.DisputeEvent, outbox entity.OutboxEvent)) *MockRepositoryDispute_CreateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Dispute), args[2].(entity.DisputeEvent), args[3].(entity.OutboxEvent))
	})
	return _c
}

func (_c *MockRepositoryDispute_CreateTx_Call) Return(_a0 entity.Dispute, _a1 error) *MockRepositoryDispute_CreateTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryDispute_CreateTx_Call) RunAndReturn(run func(context.Context, entity.Dispute, entity.DisputeEvent, entity.OutboxEvent) (entity.Dispute, error)) *MockRepositoryDispute_CreateTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRepositoryDispute) GetByID(ctx context.Context, id uuid.UUID) (entity.Dispute, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Dispute, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Dispute); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Dispute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryDispute_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepositoryDispute_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepositoryDispute_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepositoryDispute_GetByID_Call {
	return &MockRepositoryDispute_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepositoryDispute_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepositoryDispute_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryDispute_GetByID_Call) Return(_a0 entity.Dispute, _a1 error) *MockRepositoryDispute_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryDispute_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Dispute, error)) *MockRepositoryDispute_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTrade provides a mock function with given fields: ctx, tradeID
func (_m *MockRepositoryDispute) GetByTrade(ctx context.Context, tradeID string) (entity.Dispute, error) {
	ret := _m.Called(ctx, tradeID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTrade")
	}

	var r0 entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Dispute, error)); ok {
		return rf(ctx, tradeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Dispute); ok {
		r0 = rf(ctx, tradeID)
	} else {
		r0 = ret.Get(0).(entity.Dispute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tradeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryDispute_GetByTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTrade'
type MockRepositoryDispute_GetByTrade_Call struct {
	*mock.Call
}

// GetByTrade is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID string
func (_e *MockRepositoryDispute_Expecter) GetByTrade(ctx interface{}, tradeID interface{}) *MockRepositoryDispute_GetByTrade_Call {
	return &MockRepositoryDispute_GetByTrade_Call{Call: _e.mock.On("GetByTrade", ctx, tradeID)}
}

func (_c *MockRepositoryDispute_GetByTrade_Call) Run(run func(ctx context.Context, tradeID string)) *MockRepositoryDispute_GetByTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryDispute_GetByTrade_Call) Return(_a0 entity.Dispute, _a1 error) *MockRepositoryDispute_GetByTrade_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryDispute_GetByTrade_Call) RunAndReturn(run func(context.Context, string) (entity.Dispute, error)) *MockRepositoryDispute_GetByTrade_Call {
	_c.Call.Return(run)
	return _c
}

// ListByState provides a mock function with given fields: ctx, state
func (_m *MockRepositoryDispute) ListByState(ctx context.Context, state entity.State) ([]entity.Dispute, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for ListByState")
	}

	var r0 []entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.State) ([]entity.Dispute, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.State) []entity.Dispute); ok {
		r0 = rf(ctx, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Dispute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.State) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryDispute_ListByState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByState'
type MockRepositoryDispute_ListByState_Call struct {
	*mock.Call
}

// ListByState is a helper method to define mock.On call
//   - ctx context.Context
//   - state entity.State
func (_e *MockRepositoryDispute_Expecter) ListByState(ctx interface{}, state interface{}) *MockRepositoryDispute_ListByState_Call {
	return &MockRepositoryDispute_ListByState_Call{Call: _e.mock.On("ListByState", ctx, state)}
}

func (_c *MockRepositoryDispute_ListByState_Call) Run(run func(ctx context.Context, state entity.State)) *MockRepositoryDispute_ListByState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.State))
	})
	return _c
}

func (_c *MockRepositoryDispute_ListByState_Call) Return(_a0 []entity.Dispute, _a1 error) *MockRepositoryDispute_ListByState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryDispute_ListByState_Call) RunAndReturn(run func(context.Context, entity.State) ([]entity.Dispute, error)) *MockRepositoryDispute_ListByState_Call {
	_c.Call.Return(run)
	return _c
}

// ListEvents provides a mock function with given fields: ctx, disputeID
func (_m *MockRepositoryDispute) ListEvents(ctx context.Context, disputeID uuid.UUID) ([]entity.DisputeEvent, error) {
	ret := _m.Called(ctx, disputeID)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 []entity.DisputeEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.DisputeEvent, error)); ok {
		return rf(ctx, disputeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.DisputeEvent); ok {
		r0 = rf(ctx, disputeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.DisputeEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, disputeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryDispute_ListEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvents'
type MockRepositoryDispute_ListEvents_Call struct {
	*mock.Call
}

// ListEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - disputeID uuid.UUID
func (_e *MockRepositoryDispute_Expecter) ListEvents(ctx interface{}, disputeID interface{}) *MockRepositoryDispute_ListEvents_Call {
	return &MockRepositoryDispute_ListEvents_Call{Call: _e.mock.On("ListEvents", ctx, disputeID)}
}

func (_c *MockRepositoryDispute_ListEvents_Call) Run(run func(ctx context.Context, disputeID uuid.UUID)) *MockRepositoryDispute_ListEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryDispute_ListEvents_Call) Return(_a0 []entity.DisputeEvent, _a1 error) *MockRepositoryDispute_ListEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryDispute_ListEvents_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.DisputeEvent, error)) *MockRepositoryDispute_ListEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveTx provides a mock function with given fields: ctx, id, from, ruling, ruledBy, audit, outbox
func (_m *MockRepositoryDispute) ResolveTx(ctx context.Context, id uuid.UUID, from entity.State, ruling entity.Ruling, ruledBy uuid.UUID, audit entity.DisputeEvent, outbox entity.OutboxEvent) (entity.Dispute, error) {
	ret := _m.Called(ctx, id, from, ruling, ruledBy, audit, outbox)

	if len(ret) == 0 {
		panic("no return value specified for ResolveTx")
	}

	var r0 entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.State, entity.Ruling, uuid.UUID, entity.DisputeEvent, entity.OutboxEvent) (entity.Dispute, error)); ok {
		return rf(ctx, id, from, ruling, ruledBy, audit, outbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.State, entity.Ruling, uuid.UUID, entity.DisputeEvent, entity.OutboxEvent) entity.Dispute); ok {
		r0 = rf(ctx, id, from, ruling, ruledBy, audit, outbox)
	} else {
		r0 = ret.Get(0).(entity.Dispute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.State, entity.Ruling, uuid.UUID, entity.DisputeEvent, entity.OutboxEvent) error); ok {
		r1 = rf(ctx, id, from, ruling, ruledBy, audit, outbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryDispute_ResolveTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveTx'
type MockRepositoryDispute_ResolveTx_Call struct {
	*mock.Call
}

// ResolveTx is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - from entity.State
//   - ruling entity.Ruling
//   - ruledBy uuid.UUID
//   - audit entity.DisputeEvent
//   - outbox entity.OutboxEvent
func (_e *MockRepositoryDispute_Expecter) ResolveTx(ctx interface{}, id interface{}, from interface{}, ruling interface{}, ruledBy interface{}, audit interface{}, outbox interface{}) *MockRepositoryDispute_ResolveTx_Call {
	return &MockRepositoryDispute_ResolveTx_Call{Call: _e.mock.On("ResolveTx", ctx, id, from, ruling, ruledBy, audit, outbox)}
}

func (_c *MockRepositoryDispute_ResolveTx_Call) Run(run func(ctx context.Context, id uuid.UUID, from entity.State, ruling entity.Ruling, ruledBy uuid.UUID, audit entity.DisputeEvent, outbox entity.OutboxEvent)) *MockRepositoryDispute_ResolveTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.State), args[3].(entity.Ruling), args[4].(uuid.UUID), args[5].(entity.DisputeEvent), args[6].(entity.OutboxEvent))
	})
	return _c
}

func (_c *MockRepositoryDispute_ResolveTx_Call) Return(_a0 entity.Dispute, _a1 error) *MockRepositoryDispute_ResolveTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryDispute_ResolveTx_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.State, entity.Ruling, uuid.UUID, entity.DisputeEvent, entity.OutboxEvent) (entity.Dispute, error)) *MockRepositoryDispute_ResolveTx_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionTx provides a mock function with given fields: ctx, id, from, to, audit
func (_m *MockRepositoryDispute) TransitionTx(ctx context.Context, id uuid.UUID, from entity.State, to entity.State, audit entity.DisputeEvent) (entity.Dispute, error) {
	ret := _m.Called(ctx, id, from, to, audit)

	if len(ret) == 0 {
		panic("no return value specified for TransitionTx")
	}

	var r0 entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.State, entity.State, entity.DisputeEvent) (entity.Dispute, error)); ok {
		return rf(ctx, id, from, to, audit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.State, entity.State, entity.DisputeEvent) entity.Dispute); ok {
		r0 = rf(ctx, id, from, to, audit)
	} else {
		r0 = ret.Get(0).(entity.Dispute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.State, entity.State, entity.DisputeEvent) error); ok {
		r1 = rf(ctx, id, from, to, audit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryDispute_TransitionTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionTx'
type MockRepositoryDispute_TransitionTx_Call struct {
	*mock.Call
}

// TransitionTx is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - from entity.State
//   - to entity.State
//   - audit entity.DisputeEvent
func (_e *MockRepositoryDispute_Expecter) TransitionTx(ctx interface{}, id interface{}, from interface{}, to interface{}, audit interface{}) *MockRepositoryDispute_TransitionTx_Call {
	return &MockRepositoryDispute_TransitionTx_Call{Call: _e.mock.On("TransitionTx", ctx, id, from, to, audit)}
}

func (_c *MockRepositoryDispute_TransitionTx_Call) Run(run func(ctx context.Context, id uuid.UUID, from entity.State, to entity.State, audit entity.DisputeEvent)) *MockRepositoryDispute_TransitionTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.State), args[3].(entity.State), args[4].(entity.DisputeEvent))
	})
	return _c
}

func (_c *MockRepositoryDispute_TransitionTx_Call) Return(_a0 entity.Dispute, _a1 error) *MockRepositoryDispute_TransitionTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryDispute_TransitionTx_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.State, entity.State, entity.DisputeEvent) (entity.Dispute, error)) *MockRepositoryDispute_TransitionTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryDispute creates a new instance of MockRepositoryDispute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryDispute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryDispute {
	mock := &MockRepositoryDispute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
