// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	biz "application/internal/biz"
	entity "application/internal/entity"

	uuid "github.com/google/uuid"

	mock "github.com/stretchr/testify/mock"
)

// MockUsecaseKyc is an autogenerated mock type for the UsecaseKyc type
type MockUsecaseKyc struct {
	mock.Mock
}

type MockUsecaseKyc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseKyc) EXPECT() *MockUsecaseKyc_Expecter {
	return &MockUsecaseKyc_Expecter{mock: &_m.Mock}
}

// Approve provides a mock function with given fields: ctx, submissionID, decidedBy
func (_m *MockUsecaseKyc) Approve(ctx context.Context, submissionID uuid.UUID, decidedBy uuid.UUID) (entity.Submission, error) {
	ret := _m.Called(ctx, submissionID, decidedBy)

	if len(ret) == 0 {
		panic("no return value specified for Approve")
	}

	var r0 entity.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (entity.Submission, error)); ok {
		return rf(ctx, submissionID, decidedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) entity.Submission); ok {
		r0 = rf(ctx, submissionID, decidedBy)
	} else {
		r0 = ret.Get(0).(entity.Submission)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, submissionID, decidedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseKyc_Approve_Call struct {
	*mock.Call
}

func (_e *MockUsecaseKyc_Expecter) Approve(ctx interface{}, submissionID interface{}, decidedBy interface{}) *MockUsecaseKyc_Approve_Call {
	return &MockUsecaseKyc_Approve_Call{Call: _e.mock.On("Approve", ctx, submissionID, decidedBy)}
}

func (_c *MockUsecaseKyc_Approve_Call) Run(run func(ctx context.Context, submissionID uuid.UUID, decidedBy uuid.UUID)) *MockUsecaseKyc_Approve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseKyc_Approve_Call) Return(_a0 entity.Submission, _a1 error) *MockUsecaseKyc_Approve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseKyc_Approve_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (entity.Submission, error)) *MockUsecaseKyc_Approve_Call {
	_c.Call.Return(run)
	return _c
}

// PendingQueue provides a mock function with given fields: ctx
func (_m *MockUsecaseKyc) PendingQueue(ctx context.Context) ([]entity.Submission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PendingQueue")
	}

	var r0 []entity.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Submission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Submission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseKyc_PendingQueue_Call struct {
	*mock.Call
}

func (_e *MockUsecaseKyc_Expecter) PendingQueue(ctx interface{}) *MockUsecaseKyc_PendingQueue_Call {
	return &MockUsecaseKyc_PendingQueue_Call{Call: _e.mock.On("PendingQueue", ctx)}
}

func (_c *MockUsecaseKyc_PendingQueue_Call) Run(run func(ctx context.Context)) *MockUsecaseKyc_PendingQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsecaseKyc_PendingQueue_Call) Return(_a0 []entity.Submission, _a1 error) *MockUsecaseKyc_PendingQueue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseKyc_PendingQueue_Call) RunAndReturn(run func(context.Context) ([]entity.Submission, error)) *MockUsecaseKyc_PendingQueue_Call {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function with given fields: ctx, p
func (_m *MockUsecaseKyc) Reject(ctx context.Context, p biz.RejectParams) (entity.Submission, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 entity.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.RejectParams) (entity.Submission, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.RejectParams) entity.Submission); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(entity.Submission)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.RejectParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseKyc_Reject_Call struct {
	*mock.Call
}

func (_e *MockUsecaseKyc_Expecter) Reject(ctx interface{}, p interface{}) *MockUsecaseKyc_Reject_Call {
	return &MockUsecaseKyc_Reject_Call{Call: _e.mock.On("Reject", ctx, p)}
}

func (_c *MockUsecaseKyc_Reject_Call) Run(run func(ctx context.Context, p biz.RejectParams)) *MockUsecaseKyc_Reject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.RejectParams))
	})
	return _c
}

func (_c *MockUsecaseKyc_Reject_Call) Return(_a0 entity.Submission, _a1 error) *MockUsecaseKyc_Reject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseKyc_Reject_Call) RunAndReturn(run func(context.Context, biz.RejectParams) (entity.Submission, error)) *MockUsecaseKyc_Reject_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, p
func (_m *MockUsecaseKyc) Start(ctx context.Context, p biz.StartParams) (biz.StartResult, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 biz.StartResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.StartParams) (biz.StartResult, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.StartParams) biz.StartResult); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(biz.StartResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.StartParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseKyc_Start_Call struct {
	*mock.Call
}

func (_e *MockUsecaseKyc_Expecter) Start(ctx interface{}, p interface{}) *MockUsecaseKyc_Start_Call {
	return &MockUsecaseKyc_Start_Call{Call: _e.mock.On("Start", ctx, p)}
}

func (_c *MockUsecaseKyc_Start_Call) Run(run func(ctx context.Context, p biz.StartParams)) *MockUsecaseKyc_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.StartParams))
	})
	return _c
}

func (_c *MockUsecaseKyc_Start_Call) Return(_a0 biz.StartResult, _a1 error) *MockUsecaseKyc_Start_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseKyc_Start_Call) RunAndReturn(run func(context.Context, biz.StartParams) (biz.StartResult, error)) *MockUsecaseKyc_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with given fields: ctx, accountID
func (_m *MockUsecaseKyc) Status(ctx context.Context, accountID uuid.UUID) (entity.Submission, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 entity.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Submission, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Submission); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(entity.Submission)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseKyc_Status_Call struct {
	*mock.Call
}

func (_e *MockUsecaseKyc_Expecter) Status(ctx interface{}, accountID interface{}) *MockUsecaseKyc_Status_Call {
	return &MockUsecaseKyc_Status_Call{Call: _e.mock.On("Status", ctx, accountID)}
}

func (_c *MockUsecaseKyc_Status_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockUsecaseKyc_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseKyc_Status_Call) Return(_a0 entity.Submission, _a1 error) *MockUsecaseKyc_Status_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseKyc_Status_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Submission, error)) *MockUsecaseKyc_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: ctx, accountID, code
func (_m *MockUsecaseKyc) Verify(ctx context.Context, accountID uuid.UUID, code string) (entity.Submission, error) {
	ret := _m.Called(ctx, accountID, code)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 entity.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (entity.Submission, error)); ok {
		return rf(ctx, accountID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) entity.Submission); ok {
		r0 = rf(ctx, accountID, code)
	} else {
		r0 = ret.Get(0).(entity.Submission)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, accountID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseKyc_Verify_Call struct {
	*mock.Call
}

func (_e *MockUsecaseKyc_Expecter) Verify(ctx interface{}, accountID interface{}, code interface{}) *MockUsecaseKyc_Verify_Call {
	return &MockUsecaseKyc_Verify_Call{Call: _e.mock.On("Verify", ctx, accountID, code)}
}

func (_c *MockUsecaseKyc_Verify_Call) Run(run func(ctx context.Context, accountID uuid.UUID, code string)) *MockUsecaseKyc_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseKyc_Verify_Call) Return(_a0 entity.Submission, _a1 error) *MockUsecaseKyc_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseKyc_Verify_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (entity.Submission, error)) *MockUsecaseKyc_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseKyc creates a new instance of MockUsecaseKyc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseKyc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseKyc {
	mock := &MockUsecaseKyc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
