// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	entity "application/internal/entity"
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseLot is an autogenerated mock type for the UsecaseLot type
type MockUsecaseLot struct {
	mock.Mock
}

type MockUsecaseLot_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseLot) EXPECT() *MockUsecaseLot_Expecter {
	return &MockUsecaseLot_Expecter{mock: &_m.Mock}
}

// GetWeekly provides a mock function with given fields: ctx, week
func (_m *MockUsecaseLot) GetWeekly(ctx context.Context, week string) ([]entity.Lot, error) {
	ret := _m.Called(ctx, week)

	if len(ret) == 0 {
		panic("no return value specified for GetWeekly")
	}

	var r0 []entity.Lot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.Lot, error)); ok {
		return rf(ctx, week)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.Lot); ok {
		r0 = rf(ctx, week)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Lot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, week)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseLot_GetWeekly_Call struct {
	*mock.Call
}

func (_e *MockUsecaseLot_Expecter) GetWeekly(ctx interface{}, week interface{}) *MockUsecaseLot_GetWeekly_Call {
	return &MockUsecaseLot_GetWeekly_Call{Call: _e.mock.On("GetWeekly", ctx, week)}
}

func (_c *MockUsecaseLot_GetWeekly_Call) Run(run func(ctx context.Context, week string)) *MockUsecaseLot_GetWeekly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsecaseLot_GetWeekly_Call) Return(_a0 []entity.Lot, _a1 error) *MockUsecaseLot_GetWeekly_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseLot_GetWeekly_Call) RunAndReturn(run func(context.Context, string) ([]entity.Lot, error)) *MockUsecaseLot_GetWeekly_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUsecaseLot) Get(ctx context.Context, id uuid.UUID) (entity.Lot, []entity.Attestation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Lot
	var r1 []entity.Attestation
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Lot, []entity.Attestation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Lot); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Lot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) []entity.Attestation); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]entity.Attestation)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type MockUsecaseLot_Get_Call struct {
	*mock.Call
}

func (_e *MockUsecaseLot_Expecter) Get(ctx interface{}, id interface{}) *MockUsecaseLot_Get_Call {
	return &MockUsecaseLot_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUsecaseLot_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseLot_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseLot_Get_Call) Return(_a0 entity.Lot, _a1 []entity.Attestation, _a2 error) *MockUsecaseLot_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUsecaseLot_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Lot, []entity.Attestation, error)) *MockUsecaseLot_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockUsecaseLot) List(ctx context.Context, filter biz.LotListFilter) ([]entity.Lot, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Lot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.LotListFilter) ([]entity.Lot, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.LotListFilter) []entity.Lot); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Lot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.LotListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseLot_List_Call struct {
	*mock.Call
}

func (_e *MockUsecaseLot_Expecter) List(ctx interface{}, filter interface{}) *MockUsecaseLot_List_Call {
	return &MockUsecaseLot_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockUsecaseLot_List_Call) Run(run func(ctx context.Context, filter biz.LotListFilter)) *MockUsecaseLot_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.LotListFilter))
	})
	return _c
}

func (_c *MockUsecaseLot_List_Call) Return(_a0 []entity.Lot, _a1 error) *MockUsecaseLot_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseLot_List_Call) RunAndReturn(run func(context.Context, biz.LotListFilter) ([]entity.Lot, error)) *MockUsecaseLot_List_Call {
	_c.Call.Return(run)
	return _c
}

// Attest provides a mock function with given fields: ctx, lotID, in
func (_m *MockUsecaseLot) Attest(ctx context.Context, lotID uuid.UUID, in biz.AttestInput) (entity.Attestation, error) {
	ret := _m.Called(ctx, lotID, in)

	if len(ret) == 0 {
		panic("no return value specified for Attest")
	}

	var r0 entity.Attestation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.AttestInput) (entity.Attestation, error)); ok {
		return rf(ctx, lotID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.AttestInput) entity.Attestation); ok {
		r0 = rf(ctx, lotID, in)
	} else {
		r0 = ret.Get(0).(entity.Attestation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, biz.AttestInput) error); ok {
		r1 = rf(ctx, lotID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseLot_Attest_Call struct {
	*mock.Call
}

func (_e *MockUsecaseLot_Expecter) Attest(ctx interface{}, lotID interface{}, in interface{}) *MockUsecaseLot_Attest_Call {
	return &MockUsecaseLot_Attest_Call{Call: _e.mock.On("Attest", ctx, lotID, in)}
}

func (_c *MockUsecaseLot_Attest_Call) Run(run func(ctx context.Context, lotID uuid.UUID, in biz.AttestInput)) *MockUsecaseLot_Attest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(biz.AttestInput))
	})
	return _c
}

func (_c *MockUsecaseLot_Attest_Call) Return(_a0 entity.Attestation, _a1 error) *MockUsecaseLot_Attest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseLot_Attest_Call) RunAndReturn(run func(context.Context, uuid.UUID, biz.AttestInput) (entity.Attestation, error)) *MockUsecaseLot_Attest_Call {
	_c.Call.Return(run)
	return _c
}

// Certify provides a mock function with given fields: ctx, lotID
func (_m *MockUsecaseLot) Certify(ctx context.Context, lotID uuid.UUID) (entity.Lot, error) {
	ret := _m.Called(ctx, lotID)

	if len(ret) == 0 {
		panic("no return value specified for Certify")
	}

	var r0 entity.Lot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Lot, error)); ok {
		return rf(ctx, lotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Lot); ok {
		r0 = rf(ctx, lotID)
	} else {
		r0 = ret.Get(0).(entity.Lot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, lotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseLot_Certify_Call struct {
	*mock.Call
}

func (_e *MockUsecaseLot_Expecter) Certify(ctx interface{}, lotID interface{}) *MockUsecaseLot_Certify_Call {
	return &MockUsecaseLot_Certify_Call{Call: _e.mock.On("Certify", ctx, lotID)}
}

func (_c *MockUsecaseLot_Certify_Call) Run(run func(ctx context.Context, lotID uuid.UUID)) *MockUsecaseLot_Certify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseLot_Certify_Call) Return(_a0 entity.Lot, _a1 error) *MockUsecaseLot_Certify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseLot_Certify_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Lot, error)) *MockUsecaseLot_Certify_Call {
	_c.Call.Return(run)
	return _c
}

// Schedule provides a mock function with given fields: ctx, lotID, scheduledAt
func (_m *MockUsecaseLot) Schedule(ctx context.Context, lotID uuid.UUID, scheduledAt time.Time) (entity.Lot, error) {
	ret := _m.Called(ctx, lotID, scheduledAt)

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 entity.Lot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (entity.Lot, error)); ok {
		return rf(ctx, lotID, scheduledAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) entity.Lot); ok {
		r0 = rf(ctx, lotID, scheduledAt)
	} else {
		r0 = ret.Get(0).(entity.Lot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, lotID, scheduledAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockUsecaseLot_Schedule_Call struct {
	*mock.Call
}

func (_e *MockUsecaseLot_Expecter) Schedule(ctx interface{}, lotID interface{}, scheduledAt interface{}) *MockUsecaseLot_Schedule_Call {
	return &MockUsecaseLot_Schedule_Call{Call: _e.mock.On("Schedule", ctx, lotID, scheduledAt)}
}

func (_c *MockUsecaseLot_Schedule_Call) Run(run func(ctx context.Context, lotID uuid.UUID, scheduledAt time.Time)) *MockUsecaseLot_Schedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockUsecaseLot_Schedule_Call) Return(_a0 entity.Lot, _a1 error) *MockUsecaseLot_Schedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseLot_Schedule_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (entity.Lot, error)) *MockUsecaseLot_Schedule_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFromObjectListed provides a mock function with given fields: ctx, in, idempotencyKey
func (_m *MockUsecaseLot) CreateFromObjectListed(ctx context.Context, in biz.ObjectListedInput, idempotencyKey string) error {
	ret := _m.Called(ctx, in, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromObjectListed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.ObjectListedInput, string) error); ok {
		r0 = rf(ctx, in, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockUsecaseLot_CreateFromObjectListed_Call struct {
	*mock.Call
}

func (_e *MockUsecaseLot_Expecter) CreateFromObjectListed(ctx interface{}, in interface{}, idempotencyKey interface{}) *MockUsecaseLot_CreateFromObjectListed_Call {
	return &MockUsecaseLot_CreateFromObjectListed_Call{Call: _e.mock.On("CreateFromObjectListed", ctx, in, idempotencyKey)}
}

func (_c *MockUsecaseLot_CreateFromObjectListed_Call) Run(run func(ctx context.Context, in biz.ObjectListedInput, idempotencyKey string)) *MockUsecaseLot_CreateFromObjectListed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.ObjectListedInput), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseLot_CreateFromObjectListed_Call) Return(_a0 error) *MockUsecaseLot_CreateFromObjectListed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseLot_CreateFromObjectListed_Call) RunAndReturn(run func(context.Context, biz.ObjectListedInput, string) error) *MockUsecaseLot_CreateFromObjectListed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseLot creates a new instance of MockUsecaseLot. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseLot(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseLot {
	mock := &MockUsecaseLot{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
