// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://aban.io/support",
            "email": "info@aban.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apis/bids/buy": {
            "post": {
                "description": "Records a credit-package purchase atomically (the USDC charge + the credit grant). Emits bids.purchased. Idempotent on idempotencyKey. Unknown package -\u003e RESOURCE_INVALID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids"
                ],
                "summary": "Buy bid credits",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authenticated account UUID (gateway-injected)",
                        "name": "X-Account-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Package id (+ optional idempotency key)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BuyBidsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BuyBidsResp"
                        }
                    },
                    "400": {
                        "description": "Unknown package / bad body",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/apis/bids/packages": {
            "get": {
                "description": "Lists the purchasable bid-credit packages. PUBLIC. Each credit = $1; price is USDC cents.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids"
                ],
                "summary": "Credit packages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.PackageResp"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/apis/bids/wallet": {
            "get": {
                "description": "Returns the authenticated account's bid-credit balance (whole credits, $1 each) plus recent purchases and debits. Balance is read-through, never recomputed. Subject from the gateway-injected X-Account-Id header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids"
                ],
                "summary": "Bid-credit wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authenticated account UUID (gateway-injected)",
                        "name": "X-Account-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.WalletResp"
                        }
                    },
                    "401": {
                        "description": "Unauthenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/apis/internal/bids/debit": {
            "post": {
                "description": "Called by auction-passive BEFORE recording a bid. Spends ` + "`" + `amount` + "`" + ` credits. Insufficient balance -\u003e RESOURCE_INVALID (\"out of credits\"). Idempotent on idempotencyKey: a replay returns the original debit (HTTP 200, same body), never double-burns. Emits bids.debited.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids-internal"
                ],
                "summary": "Debit a bid credit (internal)",
                "parameters": [
                    {
                        "description": "Account, amount, idempotency key, auction",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DebitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DebitResultResp"
                        }
                    },
                    "400": {
                        "description": "Out of credits / bad body",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz/liveness": {
            "get": {
                "description": "Check the liveness of the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthz"
                ],
                "summary": "Healthz Liveness",
                "operationId": "healthz-liveness",
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/healthz/panic": {
            "get": {
                "tags": [
                    "healthz"
                ],
                "summary": "Panic for test",
                "responses": {
                    "500": {
                        "description": "panic",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz/rediness": {
            "get": {
                "description": "Check the readiness of the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthz"
                ],
                "summary": "Healthz Readiness",
                "operationId": "healthz-rediness",
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/healthz/sleep/{time}": {
            "get": {
                "tags": [
                    "healthz"
                ],
                "summary": "Long Run for test",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Time to sleep, e.g. 30s",
                        "name": "time",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BuyBidsRequest": {
            "type": "object",
            "required": [
                "packageId"
            ],
            "properties": {
                "idempotencyKey": {
                    "type": "string"
                },
                "packageId": {
                    "type": "string"
                }
            }
        },
        "dto.BuyBidsResp": {
            "type": "object",
            "properties": {
                "balanceCredits": {
                    "type": "integer"
                },
                "creditsGranted": {
                    "type": "integer"
                },
                "usdcChargedCents": {
                    "type": "integer"
                }
            }
        },
        "dto.DebitRequest": {
            "type": "object",
            "required": [
                "accountId",
                "amount",
                "auctionId",
                "idempotencyKey"
            ],
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "amount": {
                    "type": "integer"
                },
                "auctionId": {
                    "type": "string"
                },
                "idempotencyKey": {
                    "type": "string"
                }
            }
        },
        "dto.DebitResp": {
            "type": "object",
            "properties": {
                "amountCredits": {
                    "type": "integer"
                },
                "auctionId": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "ISO-8601 UTC",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "idempotencyKey": {
                    "type": "string"
                }
            }
        },
        "dto.DebitResultResp": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "balanceCredits": {
                    "type": "integer"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                }
            }
        },
        "dto.PackageResp": {
            "type": "object",
            "properties": {
                "bestValue": {
                    "type": "boolean"
                },
                "credits": {
                    "description": "whole credits granted",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "priceCents": {
                    "description": "USDC cents",
                    "type": "integer"
                }
            }
        },
        "dto.PurchaseResp": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "ISO-8601 UTC",
                    "type": "string"
                },
                "creditsGranted": {
                    "description": "whole credits",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "packageId": {
                    "type": "string"
                },
                "usdcChargedCents": {
                    "description": "USDC cents",
                    "type": "integer"
                }
            }
        },
        "dto.WalletResp": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "balanceCredits": {
                    "type": "integer"
                },
                "debits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DebitResp"
                    }
                },
                "purchases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PurchaseResp"
                    }
                },
                "updatedAt": {
                    "description": "ISO-8601 UTC",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger",
	Description:      "API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
