// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryEscrow is an autogenerated mock type for the RepositoryEscrow type
type MockRepositoryEscrow struct {
	mock.Mock
}

type MockRepositoryEscrow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryEscrow) EXPECT() *MockRepositoryEscrow_Expecter {
	return &MockRepositoryEscrow_Expecter{mock: &_m.Mock}
}

// GetTrade provides a mock function with given fields: ctx, tradeID
func (_m *MockRepositoryEscrow) GetTrade(ctx context.Context, tradeID uuid.UUID) (entity.EscrowTrade, error) {
	ret := _m.Called(ctx, tradeID)

	if len(ret) == 0 {
		panic("no return value specified for GetTrade")
	}

	var r0 entity.EscrowTrade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.EscrowTrade, error)); ok {
		return rf(ctx, tradeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.EscrowTrade); ok {
		r0 = rf(ctx, tradeID)
	} else {
		r0 = ret.Get(0).(entity.EscrowTrade)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tradeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryEscrow_GetTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrade'
type MockRepositoryEscrow_GetTrade_Call struct {
	*mock.Call
}

// GetTrade is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID uuid.UUID
func (_e *MockRepositoryEscrow_Expecter) GetTrade(ctx interface{}, tradeID interface{}) *MockRepositoryEscrow_GetTrade_Call {
	return &MockRepositoryEscrow_GetTrade_Call{Call: _e.mock.On("GetTrade", ctx, tradeID)}
}

func (_c *MockRepositoryEscrow_GetTrade_Call) Run(run func(ctx context.Context, tradeID uuid.UUID)) *MockRepositoryEscrow_GetTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryEscrow_GetTrade_Call) Return(_a0 entity.EscrowTrade, _a1 error) *MockRepositoryEscrow_GetTrade_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryEscrow_GetTrade_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.EscrowTrade, error)) *MockRepositoryEscrow_GetTrade_Call {
	_c.Call.Return(run)
	return _c
}

// ListEntries provides a mock function with given fields: ctx, tradeID
func (_m *MockRepositoryEscrow) ListEntries(ctx context.Context, tradeID uuid.UUID) ([]entity.LedgerEntry, error) {
	ret := _m.Called(ctx, tradeID)

	if len(ret) == 0 {
		panic("no return value specified for ListEntries")
	}

	var r0 []entity.LedgerEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.LedgerEntry, error)); ok {
		return rf(ctx, tradeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.LedgerEntry); ok {
		r0 = rf(ctx, tradeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tradeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryEscrow_ListEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEntries'
type MockRepositoryEscrow_ListEntries_Call struct {
	*mock.Call
}

// ListEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID uuid.UUID
func (_e *MockRepositoryEscrow_Expecter) ListEntries(ctx interface{}, tradeID interface{}) *MockRepositoryEscrow_ListEntries_Call {
	return &MockRepositoryEscrow_ListEntries_Call{Call: _e.mock.On("ListEntries", ctx, tradeID)}
}

func (_c *MockRepositoryEscrow_ListEntries_Call) Run(run func(ctx context.Context, tradeID uuid.UUID)) *MockRepositoryEscrow_ListEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryEscrow_ListEntries_Call) Return(_a0 []entity.LedgerEntry, _a1 error) *MockRepositoryEscrow_ListEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryEscrow_ListEntries_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.LedgerEntry, error)) *MockRepositoryEscrow_ListEntries_Call {
	_c.Call.Return(run)
	return _c
}

// Balances provides a mock function with given fields: ctx, tradeID
func (_m *MockRepositoryEscrow) Balances(ctx context.Context, tradeID uuid.UUID) ([]entity.ParticipantBalance, error) {
	ret := _m.Called(ctx, tradeID)

	if len(ret) == 0 {
		panic("no return value specified for Balances")
	}

	var r0 []entity.ParticipantBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.ParticipantBalance, error)); ok {
		return rf(ctx, tradeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.ParticipantBalance); ok {
		r0 = rf(ctx, tradeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ParticipantBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tradeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryEscrow_Balances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Balances'
type MockRepositoryEscrow_Balances_Call struct {
	*mock.Call
}

// Balances is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID uuid.UUID
func (_e *MockRepositoryEscrow_Expecter) Balances(ctx interface{}, tradeID interface{}) *MockRepositoryEscrow_Balances_Call {
	return &MockRepositoryEscrow_Balances_Call{Call: _e.mock.On("Balances", ctx, tradeID)}
}

func (_c *MockRepositoryEscrow_Balances_Call) Run(run func(ctx context.Context, tradeID uuid.UUID)) *MockRepositoryEscrow_Balances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryEscrow_Balances_Call) Return(_a0 []entity.ParticipantBalance, _a1 error) *MockRepositoryEscrow_Balances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryEscrow_Balances_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.ParticipantBalance, error)) *MockRepositoryEscrow_Balances_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTradeTx provides a mock function with given fields: ctx, trade, entries, outbox
func (_m *MockRepositoryEscrow) CreateTradeTx(ctx context.Context, trade entity.EscrowTrade, entries []entity.LedgerEntry, outbox *entity.OutboxEvent) error {
	ret := _m.Called(ctx, trade, entries, outbox)

	if len(ret) == 0 {
		panic("no return value specified for CreateTradeTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.EscrowTrade, []entity.LedgerEntry, *entity.OutboxEvent) error); ok {
		r0 = rf(ctx, trade, entries, outbox)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryEscrow_CreateTradeTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTradeTx'
type MockRepositoryEscrow_CreateTradeTx_Call struct {
	*mock.Call
}

// CreateTradeTx is a helper method to define mock.On call
//   - ctx context.Context
//   - trade entity.EscrowTrade
//   - entries []entity.LedgerEntry
//   - outbox *entity.OutboxEvent
func (_e *MockRepositoryEscrow_Expecter) CreateTradeTx(ctx interface{}, trade interface{}, entries interface{}, outbox interface{}) *MockRepositoryEscrow_CreateTradeTx_Call {
	return &MockRepositoryEscrow_CreateTradeTx_Call{Call: _e.mock.On("CreateTradeTx", ctx, trade, entries, outbox)}
}

func (_c *MockRepositoryEscrow_CreateTradeTx_Call) Run(run func(ctx context.Context, trade entity.EscrowTrade, entries []entity.LedgerEntry, outbox *entity.OutboxEvent)) *MockRepositoryEscrow_CreateTradeTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var entries []entity.LedgerEntry
		if args[2] != nil {
			entries = args[2].([]entity.LedgerEntry)
		}
		var outbox *entity.OutboxEvent
		if args[3] != nil {
			outbox = args[3].(*entity.OutboxEvent)
		}
		run(args[0].(context.Context), args[1].(entity.EscrowTrade), entries, outbox)
	})
	return _c
}

func (_c *MockRepositoryEscrow_CreateTradeTx_Call) Return(_a0 error) *MockRepositoryEscrow_CreateTradeTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryEscrow_CreateTradeTx_Call) RunAndReturn(run func(context.Context, entity.EscrowTrade, []entity.LedgerEntry, *entity.OutboxEvent) error) *MockRepositoryEscrow_CreateTradeTx_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionTx provides a mock function with given fields: ctx, tradeID, from, to, upd, entries, outbox
func (_m *MockRepositoryEscrow) TransitionTx(ctx context.Context, tradeID uuid.UUID, from entity.EscrowState, to entity.EscrowState, upd biz.TradeUpdate, entries []entity.LedgerEntry, outbox *entity.OutboxEvent) (entity.EscrowTrade, error) {
	ret := _m.Called(ctx, tradeID, from, to, upd, entries, outbox)

	if len(ret) == 0 {
		panic("no return value specified for TransitionTx")
	}

	var r0 entity.EscrowTrade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.EscrowState, entity.EscrowState, biz.TradeUpdate, []entity.LedgerEntry, *entity.OutboxEvent) (entity.EscrowTrade, error)); ok {
		return rf(ctx, tradeID, from, to, upd, entries, outbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.EscrowState, entity.EscrowState, biz.TradeUpdate, []entity.LedgerEntry, *entity.OutboxEvent) entity.EscrowTrade); ok {
		r0 = rf(ctx, tradeID, from, to, upd, entries, outbox)
	} else {
		r0 = ret.Get(0).(entity.EscrowTrade)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.EscrowState, entity.EscrowState, biz.TradeUpdate, []entity.LedgerEntry, *entity.OutboxEvent) error); ok {
		r1 = rf(ctx, tradeID, from, to, upd, entries, outbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryEscrow_TransitionTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionTx'
type MockRepositoryEscrow_TransitionTx_Call struct {
	*mock.Call
}

// TransitionTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID uuid.UUID
//   - from entity.EscrowState
//   - to entity.EscrowState
//   - upd biz.TradeUpdate
//   - entries []entity.LedgerEntry
//   - outbox *entity.OutboxEvent
func (_e *MockRepositoryEscrow_Expecter) TransitionTx(ctx interface{}, tradeID interface{}, from interface{}, to interface{}, upd interface{}, entries interface{}, outbox interface{}) *MockRepositoryEscrow_TransitionTx_Call {
	return &MockRepositoryEscrow_TransitionTx_Call{Call: _e.mock.On("TransitionTx", ctx, tradeID, from, to, upd, entries, outbox)}
}

func (_c *MockRepositoryEscrow_TransitionTx_Call) Run(run func(ctx context.Context, tradeID uuid.UUID, from entity.EscrowState, to entity.EscrowState, upd biz.TradeUpdate, entries []entity.LedgerEntry, outbox *entity.OutboxEvent)) *MockRepositoryEscrow_TransitionTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var entries []entity.LedgerEntry
		if args[5] != nil {
			entries = args[5].([]entity.LedgerEntry)
		}
		var outbox *entity.OutboxEvent
		if args[6] != nil {
			outbox = args[6].(*entity.OutboxEvent)
		}
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.EscrowState), args[3].(entity.EscrowState), args[4].(biz.TradeUpdate), entries, outbox)
	})
	return _c
}

func (_c *MockRepositoryEscrow_TransitionTx_Call) Return(_a0 entity.EscrowTrade, _a1 error) *MockRepositoryEscrow_TransitionTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryEscrow_TransitionTx_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.EscrowState, entity.EscrowState, biz.TradeUpdate, []entity.LedgerEntry, *entity.OutboxEvent) (entity.EscrowTrade, error)) *MockRepositoryEscrow_TransitionTx_Call {
	_c.Call.Return(run)
	return _c
}

// MarkConsumed provides a mock function with given fields: ctx, inboxKey
func (_m *MockRepositoryEscrow) MarkConsumed(ctx context.Context, inboxKey string) (bool, error) {
	ret := _m.Called(ctx, inboxKey)

	if len(ret) == 0 {
		panic("no return value specified for MarkConsumed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, inboxKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, inboxKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, inboxKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryEscrow_MarkConsumed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkConsumed'
type MockRepositoryEscrow_MarkConsumed_Call struct {
	*mock.Call
}

// MarkConsumed is a helper method to define mock.On call
//   - ctx context.Context
//   - inboxKey string
func (_e *MockRepositoryEscrow_Expecter) MarkConsumed(ctx interface{}, inboxKey interface{}) *MockRepositoryEscrow_MarkConsumed_Call {
	return &MockRepositoryEscrow_MarkConsumed_Call{Call: _e.mock.On("MarkConsumed", ctx, inboxKey)}
}

func (_c *MockRepositoryEscrow_MarkConsumed_Call) Run(run func(ctx context.Context, inboxKey string)) *MockRepositoryEscrow_MarkConsumed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryEscrow_MarkConsumed_Call) Return(_a0 bool, _a1 error) *MockRepositoryEscrow_MarkConsumed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryEscrow_MarkConsumed_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRepositoryEscrow_MarkConsumed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryEscrow creates a new instance of MockRepositoryEscrow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryEscrow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryEscrow {
	mock := &MockRepositoryEscrow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
