// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCreditDebitor is an autogenerated mock type for the CreditDebitor type
type MockCreditDebitor struct {
	mock.Mock
}

type MockCreditDebitor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreditDebitor) EXPECT() *MockCreditDebitor_Expecter {
	return &MockCreditDebitor_Expecter{mock: &_m.Mock}
}

// Debit provides a mock function with given fields: ctx, accountID, amount, idempotencyKey, auctionID
func (_m *MockCreditDebitor) Debit(ctx context.Context, accountID uuid.UUID, amount int64, idempotencyKey string, auctionID uuid.UUID) error {
	ret := _m.Called(ctx, accountID, amount, idempotencyKey, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for Debit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, string, uuid.UUID) error); ok {
		r0 = rf(ctx, accountID, amount, idempotencyKey, auctionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockCreditDebitor_Debit_Call struct {
	*mock.Call
}

func (_e *MockCreditDebitor_Expecter) Debit(ctx interface{}, accountID interface{}, amount interface{}, idempotencyKey interface{}, auctionID interface{}) *MockCreditDebitor_Debit_Call {
	return &MockCreditDebitor_Debit_Call{Call: _e.mock.On("Debit", ctx, accountID, amount, idempotencyKey, auctionID)}
}

func (_c *MockCreditDebitor_Debit_Call) Run(run func(ctx context.Context, accountID uuid.UUID, amount int64, idempotencyKey string, auctionID uuid.UUID)) *MockCreditDebitor_Debit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64), args[3].(string), args[4].(uuid.UUID))
	})
	return _c
}

func (_c *MockCreditDebitor_Debit_Call) Return(_a0 error) *MockCreditDebitor_Debit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCreditDebitor_Debit_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64, string, uuid.UUID) error) *MockCreditDebitor_Debit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreditDebitor creates a new instance of MockCreditDebitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreditDebitor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreditDebitor {
	mock := &MockCreditDebitor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
