// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseEscrow is an autogenerated mock type for the UsecaseEscrow type
type MockUsecaseEscrow struct {
	mock.Mock
}

type MockUsecaseEscrow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseEscrow) EXPECT() *MockUsecaseEscrow_Expecter {
	return &MockUsecaseEscrow_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, tradeID
func (_m *MockUsecaseEscrow) Get(ctx context.Context, tradeID uuid.UUID) (biz.TradeView, error) {
	ret := _m.Called(ctx, tradeID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 biz.TradeView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (biz.TradeView, error)); ok {
		return rf(ctx, tradeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) biz.TradeView); ok {
		r0 = rf(ctx, tradeID)
	} else {
		r0 = ret.Get(0).(biz.TradeView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tradeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseEscrow_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecaseEscrow_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID uuid.UUID
func (_e *MockUsecaseEscrow_Expecter) Get(ctx interface{}, tradeID interface{}) *MockUsecaseEscrow_Get_Call {
	return &MockUsecaseEscrow_Get_Call{Call: _e.mock.On("Get", ctx, tradeID)}
}

func (_c *MockUsecaseEscrow_Get_Call) Run(run func(ctx context.Context, tradeID uuid.UUID)) *MockUsecaseEscrow_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseEscrow_Get_Call) Return(_a0 biz.TradeView, _a1 error) *MockUsecaseEscrow_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseEscrow_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (biz.TradeView, error)) *MockUsecaseEscrow_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Fund provides a mock function with given fields: ctx, tradeID, caller, amountCents
func (_m *MockUsecaseEscrow) Fund(ctx context.Context, tradeID uuid.UUID, caller uuid.UUID, amountCents int64) (entity.EscrowTrade, error) {
	ret := _m.Called(ctx, tradeID, caller, amountCents)

	if len(ret) == 0 {
		panic("no return value specified for Fund")
	}

	var r0 entity.EscrowTrade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int64) (entity.EscrowTrade, error)); ok {
		return rf(ctx, tradeID, caller, amountCents)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int64) entity.EscrowTrade); ok {
		r0 = rf(ctx, tradeID, caller, amountCents)
	} else {
		r0 = ret.Get(0).(entity.EscrowTrade)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int64) error); ok {
		r1 = rf(ctx, tradeID, caller, amountCents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseEscrow_Fund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fund'
type MockUsecaseEscrow_Fund_Call struct {
	*mock.Call
}

// Fund is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID uuid.UUID
//   - caller uuid.UUID
//   - amountCents int64
func (_e *MockUsecaseEscrow_Expecter) Fund(ctx interface{}, tradeID interface{}, caller interface{}, amountCents interface{}) *MockUsecaseEscrow_Fund_Call {
	return &MockUsecaseEscrow_Fund_Call{Call: _e.mock.On("Fund", ctx, tradeID, caller, amountCents)}
}

func (_c *MockUsecaseEscrow_Fund_Call) Run(run func(ctx context.Context, tradeID uuid.UUID, caller uuid.UUID, amountCents int64)) *MockUsecaseEscrow_Fund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int64))
	})
	return _c
}

func (_c *MockUsecaseEscrow_Fund_Call) Return(_a0 entity.EscrowTrade, _a1 error) *MockUsecaseEscrow_Fund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseEscrow_Fund_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int64) (entity.EscrowTrade, error)) *MockUsecaseEscrow_Fund_Call {
	_c.Call.Return(run)
	return _c
}

// Confirm provides a mock function with given fields: ctx, tradeID, caller, mode
func (_m *MockUsecaseEscrow) Confirm(ctx context.Context, tradeID uuid.UUID, caller uuid.UUID, mode entity.ReleaseMode) (entity.EscrowTrade, error) {
	ret := _m.Called(ctx, tradeID, caller, mode)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 entity.EscrowTrade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, entity.ReleaseMode) (entity.EscrowTrade, error)); ok {
		return rf(ctx, tradeID, caller, mode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, entity.ReleaseMode) entity.EscrowTrade); ok {
		r0 = rf(ctx, tradeID, caller, mode)
	} else {
		r0 = ret.Get(0).(entity.EscrowTrade)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, entity.ReleaseMode) error); ok {
		r1 = rf(ctx, tradeID, caller, mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseEscrow_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockUsecaseEscrow_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID uuid.UUID
//   - caller uuid.UUID
//   - mode entity.ReleaseMode
func (_e *MockUsecaseEscrow_Expecter) Confirm(ctx interface{}, tradeID interface{}, caller interface{}, mode interface{}) *MockUsecaseEscrow_Confirm_Call {
	return &MockUsecaseEscrow_Confirm_Call{Call: _e.mock.On("Confirm", ctx, tradeID, caller, mode)}
}

func (_c *MockUsecaseEscrow_Confirm_Call) Run(run func(ctx context.Context, tradeID uuid.UUID, caller uuid.UUID, mode entity.ReleaseMode)) *MockUsecaseEscrow_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(entity.ReleaseMode))
	})
	return _c
}

func (_c *MockUsecaseEscrow_Confirm_Call) Return(_a0 entity.EscrowTrade, _a1 error) *MockUsecaseEscrow_Confirm_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseEscrow_Confirm_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, entity.ReleaseMode) (entity.EscrowTrade, error)) *MockUsecaseEscrow_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// Refund provides a mock function with given fields: ctx, tradeID, participant
func (_m *MockUsecaseEscrow) Refund(ctx context.Context, tradeID uuid.UUID, participant uuid.UUID) (entity.EscrowTrade, error) {
	ret := _m.Called(ctx, tradeID, participant)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 entity.EscrowTrade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (entity.EscrowTrade, error)); ok {
		return rf(ctx, tradeID, participant)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) entity.EscrowTrade); ok {
		r0 = rf(ctx, tradeID, participant)
	} else {
		r0 = ret.Get(0).(entity.EscrowTrade)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tradeID, participant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseEscrow_Refund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refund'
type MockUsecaseEscrow_Refund_Call struct {
	*mock.Call
}

// Refund is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID uuid.UUID
//   - participant uuid.UUID
func (_e *MockUsecaseEscrow_Expecter) Refund(ctx interface{}, tradeID interface{}, participant interface{}) *MockUsecaseEscrow_Refund_Call {
	return &MockUsecaseEscrow_Refund_Call{Call: _e.mock.On("Refund", ctx, tradeID, participant)}
}

func (_c *MockUsecaseEscrow_Refund_Call) Run(run func(ctx context.Context, tradeID uuid.UUID, participant uuid.UUID)) *MockUsecaseEscrow_Refund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseEscrow_Refund_Call) Return(_a0 entity.EscrowTrade, _a1 error) *MockUsecaseEscrow_Refund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseEscrow_Refund_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (entity.EscrowTrade, error)) *MockUsecaseEscrow_Refund_Call {
	_c.Call.Return(run)
	return _c
}

// Forfeit provides a mock function with given fields: ctx, tradeID
func (_m *MockUsecaseEscrow) Forfeit(ctx context.Context, tradeID uuid.UUID) (entity.EscrowTrade, error) {
	ret := _m.Called(ctx, tradeID)

	if len(ret) == 0 {
		panic("no return value specified for Forfeit")
	}

	var r0 entity.EscrowTrade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.EscrowTrade, error)); ok {
		return rf(ctx, tradeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.EscrowTrade); ok {
		r0 = rf(ctx, tradeID)
	} else {
		r0 = ret.Get(0).(entity.EscrowTrade)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tradeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseEscrow_Forfeit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forfeit'
type MockUsecaseEscrow_Forfeit_Call struct {
	*mock.Call
}

// Forfeit is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeID uuid.UUID
func (_e *MockUsecaseEscrow_Expecter) Forfeit(ctx interface{}, tradeID interface{}) *MockUsecaseEscrow_Forfeit_Call {
	return &MockUsecaseEscrow_Forfeit_Call{Call: _e.mock.On("Forfeit", ctx, tradeID)}
}

func (_c *MockUsecaseEscrow_Forfeit_Call) Run(run func(ctx context.Context, tradeID uuid.UUID)) *MockUsecaseEscrow_Forfeit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseEscrow_Forfeit_Call) Return(_a0 entity.EscrowTrade, _a1 error) *MockUsecaseEscrow_Forfeit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseEscrow_Forfeit_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.EscrowTrade, error)) *MockUsecaseEscrow_Forfeit_Call {
	_c.Call.Return(run)
	return _c
}

// LockRequested provides a mock function with given fields: ctx, in
func (_m *MockUsecaseEscrow) LockRequested(ctx context.Context, in biz.LockRequest) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for LockRequested")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.LockRequest) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseEscrow_LockRequested_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockRequested'
type MockUsecaseEscrow_LockRequested_Call struct {
	*mock.Call
}

// LockRequested is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.LockRequest
func (_e *MockUsecaseEscrow_Expecter) LockRequested(ctx interface{}, in interface{}) *MockUsecaseEscrow_LockRequested_Call {
	return &MockUsecaseEscrow_LockRequested_Call{Call: _e.mock.On("LockRequested", ctx, in)}
}

func (_c *MockUsecaseEscrow_LockRequested_Call) Run(run func(ctx context.Context, in biz.LockRequest)) *MockUsecaseEscrow_LockRequested_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.LockRequest))
	})
	return _c
}

func (_c *MockUsecaseEscrow_LockRequested_Call) Return(_a0 error) *MockUsecaseEscrow_LockRequested_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseEscrow_LockRequested_Call) RunAndReturn(run func(context.Context, biz.LockRequest) error) *MockUsecaseEscrow_LockRequested_Call {
	_c.Call.Return(run)
	return _c
}

// Hammer provides a mock function with given fields: ctx, in
func (_m *MockUsecaseEscrow) Hammer(ctx context.Context, in biz.HammerInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Hammer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.HammerInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseEscrow_Hammer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hammer'
type MockUsecaseEscrow_Hammer_Call struct {
	*mock.Call
}

// Hammer is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.HammerInput
func (_e *MockUsecaseEscrow_Expecter) Hammer(ctx interface{}, in interface{}) *MockUsecaseEscrow_Hammer_Call {
	return &MockUsecaseEscrow_Hammer_Call{Call: _e.mock.On("Hammer", ctx, in)}
}

func (_c *MockUsecaseEscrow_Hammer_Call) Run(run func(ctx context.Context, in biz.HammerInput)) *MockUsecaseEscrow_Hammer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.HammerInput))
	})
	return _c
}

func (_c *MockUsecaseEscrow_Hammer_Call) Return(_a0 error) *MockUsecaseEscrow_Hammer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseEscrow_Hammer_Call) RunAndReturn(run func(context.Context, biz.HammerInput) error) *MockUsecaseEscrow_Hammer_Call {
	_c.Call.Return(run)
	return _c
}

// Won provides a mock function with given fields: ctx, in
func (_m *MockUsecaseEscrow) Won(ctx context.Context, in biz.WonInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Won")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.WonInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseEscrow_Won_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Won'
type MockUsecaseEscrow_Won_Call struct {
	*mock.Call
}

// Won is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.WonInput
func (_e *MockUsecaseEscrow_Expecter) Won(ctx interface{}, in interface{}) *MockUsecaseEscrow_Won_Call {
	return &MockUsecaseEscrow_Won_Call{Call: _e.mock.On("Won", ctx, in)}
}

func (_c *MockUsecaseEscrow_Won_Call) Run(run func(ctx context.Context, in biz.WonInput)) *MockUsecaseEscrow_Won_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.WonInput))
	})
	return _c
}

func (_c *MockUsecaseEscrow_Won_Call) Return(_a0 error) *MockUsecaseEscrow_Won_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseEscrow_Won_Call) RunAndReturn(run func(context.Context, biz.WonInput) error) *MockUsecaseEscrow_Won_Call {
	_c.Call.Return(run)
	return _c
}

// DisputeResolved provides a mock function with given fields: ctx, in
func (_m *MockUsecaseEscrow) DisputeResolved(ctx context.Context, in biz.DisputeInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DisputeResolved")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.DisputeInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseEscrow_DisputeResolved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisputeResolved'
type MockUsecaseEscrow_DisputeResolved_Call struct {
	*mock.Call
}

// DisputeResolved is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.DisputeInput
func (_e *MockUsecaseEscrow_Expecter) DisputeResolved(ctx interface{}, in interface{}) *MockUsecaseEscrow_DisputeResolved_Call {
	return &MockUsecaseEscrow_DisputeResolved_Call{Call: _e.mock.On("DisputeResolved", ctx, in)}
}

func (_c *MockUsecaseEscrow_DisputeResolved_Call) Run(run func(ctx context.Context, in biz.DisputeInput)) *MockUsecaseEscrow_DisputeResolved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.DisputeInput))
	})
	return _c
}

func (_c *MockUsecaseEscrow_DisputeResolved_Call) Return(_a0 error) *MockUsecaseEscrow_DisputeResolved_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseEscrow_DisputeResolved_Call) RunAndReturn(run func(context.Context, biz.DisputeInput) error) *MockUsecaseEscrow_DisputeResolved_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseEscrow creates a new instance of MockUsecaseEscrow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseEscrow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseEscrow {
	mock := &MockUsecaseEscrow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
