// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUsecaseAuth is an autogenerated mock type for the UsecaseAuth type
type MockUsecaseAuth struct {
	mock.Mock
}

type MockUsecaseAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseAuth) EXPECT() *MockUsecaseAuth_Expecter {
	return &MockUsecaseAuth_Expecter{mock: &_m.Mock}
}

// OAuthLogin provides a mock function with given fields: ctx, provider, code
func (_m *MockUsecaseAuth) OAuthLogin(ctx context.Context, provider string, code string) (biz.AuthResult, error) {
	ret := _m.Called(ctx, provider, code)

	if len(ret) == 0 {
		panic("no return value specified for OAuthLogin")
	}

	var r0 biz.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (biz.AuthResult, error)); ok {
		return rf(ctx, provider, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) biz.AuthResult); ok {
		r0 = rf(ctx, provider, code)
	} else {
		r0 = ret.Get(0).(biz.AuthResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, provider, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuth_OAuthLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OAuthLogin'
type MockUsecaseAuth_OAuthLogin_Call struct {
	*mock.Call
}

// OAuthLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - code string
func (_e *MockUsecaseAuth_Expecter) OAuthLogin(ctx interface{}, provider interface{}, code interface{}) *MockUsecaseAuth_OAuthLogin_Call {
	return &MockUsecaseAuth_OAuthLogin_Call{Call: _e.mock.On("OAuthLogin", ctx, provider, code)}
}

func (_c *MockUsecaseAuth_OAuthLogin_Call) Run(run func(ctx context.Context, provider string, code string)) *MockUsecaseAuth_OAuthLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseAuth_OAuthLogin_Call) Return(_a0 biz.AuthResult, _a1 error) *MockUsecaseAuth_OAuthLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuth_OAuthLogin_Call) RunAndReturn(run func(context.Context, string, string) (biz.AuthResult, error)) *MockUsecaseAuth_OAuthLogin_Call {
	_c.Call.Return(run)
	return _c
}

// RequestOTP provides a mock function with given fields: ctx, mobile, purpose
func (_m *MockUsecaseAuth) RequestOTP(ctx context.Context, mobile string, purpose string) (int, string, error) {
	ret := _m.Called(ctx, mobile, purpose)

	if len(ret) == 0 {
		panic("no return value specified for RequestOTP")
	}

	var r0 int
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int, string, error)); ok {
		return rf(ctx, mobile, purpose)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = rf(ctx, mobile, purpose)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, mobile, purpose)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, mobile, purpose)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUsecaseAuth_RequestOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestOTP'
type MockUsecaseAuth_RequestOTP_Call struct {
	*mock.Call
}

// RequestOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - mobile string
//   - purpose string
func (_e *MockUsecaseAuth_Expecter) RequestOTP(ctx interface{}, mobile interface{}, purpose interface{}) *MockUsecaseAuth_RequestOTP_Call {
	return &MockUsecaseAuth_RequestOTP_Call{Call: _e.mock.On("RequestOTP", ctx, mobile, purpose)}
}

func (_c *MockUsecaseAuth_RequestOTP_Call) Run(run func(ctx context.Context, mobile string, purpose string)) *MockUsecaseAuth_RequestOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseAuth_RequestOTP_Call) Return(expiresInSecs int, devCode string, err error) *MockUsecaseAuth_RequestOTP_Call {
	_c.Call.Return(expiresInSecs, devCode, err)
	return _c
}

func (_c *MockUsecaseAuth_RequestOTP_Call) RunAndReturn(run func(context.Context, string, string) (int, string, error)) *MockUsecaseAuth_RequestOTP_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function with given fields: ctx, mobile, code
func (_m *MockUsecaseAuth) VerifyOTP(ctx context.Context, mobile string, code string) (biz.AuthResult, error) {
	ret := _m.Called(ctx, mobile, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 biz.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (biz.AuthResult, error)); ok {
		return rf(ctx, mobile, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) biz.AuthResult); ok {
		r0 = rf(ctx, mobile, code)
	} else {
		r0 = ret.Get(0).(biz.AuthResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, mobile, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuth_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type MockUsecaseAuth_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - mobile string
//   - code string
func (_e *MockUsecaseAuth_Expecter) VerifyOTP(ctx interface{}, mobile interface{}, code interface{}) *MockUsecaseAuth_VerifyOTP_Call {
	return &MockUsecaseAuth_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, mobile, code)}
}

func (_c *MockUsecaseAuth_VerifyOTP_Call) Run(run func(ctx context.Context, mobile string, code string)) *MockUsecaseAuth_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseAuth_VerifyOTP_Call) Return(_a0 biz.AuthResult, _a1 error) *MockUsecaseAuth_VerifyOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuth_VerifyOTP_Call) RunAndReturn(run func(context.Context, string, string) (biz.AuthResult, error)) *MockUsecaseAuth_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseAuth creates a new instance of MockUsecaseAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseAuth {
	mock := &MockUsecaseAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
