// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryAccount is an autogenerated mock type for the RepositoryAccount type
type MockRepositoryAccount struct {
	mock.Mock
}

type MockRepositoryAccount_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryAccount) EXPECT() *MockRepositoryAccount_Expecter {
	return &MockRepositoryAccount_Expecter{mock: &_m.Mock}
}

// EnsureExists provides a mock function with given fields: ctx, id
func (_m *MockRepositoryAccount) EnsureExists(ctx context.Context, id uuid.UUID) (entity.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for EnsureExists")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryAccount_EnsureExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureExists'
type MockRepositoryAccount_EnsureExists_Call struct {
	*mock.Call
}

// EnsureExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepositoryAccount_Expecter) EnsureExists(ctx interface{}, id interface{}) *MockRepositoryAccount_EnsureExists_Call {
	return &MockRepositoryAccount_EnsureExists_Call{Call: _e.mock.On("EnsureExists", ctx, id)}
}

func (_c *MockRepositoryAccount_EnsureExists_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepositoryAccount_EnsureExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryAccount_EnsureExists_Call) Return(_a0 entity.Account, _a1 error) *MockRepositoryAccount_EnsureExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryAccount_EnsureExists_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Account, error)) *MockRepositoryAccount_EnsureExists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRepositoryAccount) Get(ctx context.Context, id uuid.UUID) (entity.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryAccount_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepositoryAccount_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepositoryAccount_Expecter) Get(ctx interface{}, id interface{}) *MockRepositoryAccount_Get_Call {
	return &MockRepositoryAccount_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepositoryAccount_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepositoryAccount_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryAccount_Get_Call) Return(_a0 entity.Account, _a1 error) *MockRepositoryAccount_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryAccount_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Account, error)) *MockRepositoryAccount_Get_Call {
	_c.Call.Return(run)
	return _c
}

// MarkConsumed provides a mock function with given fields: ctx, inboxKey
func (_m *MockRepositoryAccount) MarkConsumed(ctx context.Context, inboxKey string) (bool, error) {
	ret := _m.Called(ctx, inboxKey)

	if len(ret) == 0 {
		panic("no return value specified for MarkConsumed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, inboxKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, inboxKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, inboxKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryAccount_MarkConsumed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkConsumed'
type MockRepositoryAccount_MarkConsumed_Call struct {
	*mock.Call
}

// MarkConsumed is a helper method to define mock.On call
//   - ctx context.Context
//   - inboxKey string
func (_e *MockRepositoryAccount_Expecter) MarkConsumed(ctx interface{}, inboxKey interface{}) *MockRepositoryAccount_MarkConsumed_Call {
	return &MockRepositoryAccount_MarkConsumed_Call{Call: _e.mock.On("MarkConsumed", ctx, inboxKey)}
}

func (_c *MockRepositoryAccount_MarkConsumed_Call) Run(run func(ctx context.Context, inboxKey string)) *MockRepositoryAccount_MarkConsumed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryAccount_MarkConsumed_Call) Return(_a0 bool, _a1 error) *MockRepositoryAccount_MarkConsumed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryAccount_MarkConsumed_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRepositoryAccount_MarkConsumed_Call {
	_c.Call.Return(run)
	return _c
}

// SetKycTx provides a mock function with given fields: ctx, id, status, inboxKey
func (_m *MockRepositoryAccount) SetKycTx(ctx context.Context, id uuid.UUID, status entity.KycState, inboxKey string) error {
	ret := _m.Called(ctx, id, status, inboxKey)

	if len(ret) == 0 {
		panic("no return value specified for SetKycTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.KycState, string) error); ok {
		r0 = rf(ctx, id, status, inboxKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryAccount_SetKycTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKycTx'
type MockRepositoryAccount_SetKycTx_Call struct {
	*mock.Call
}

// SetKycTx is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status entity.KycState
//   - inboxKey string
func (_e *MockRepositoryAccount_Expecter) SetKycTx(ctx interface{}, id interface{}, status interface{}, inboxKey interface{}) *MockRepositoryAccount_SetKycTx_Call {
	return &MockRepositoryAccount_SetKycTx_Call{Call: _e.mock.On("SetKycTx", ctx, id, status, inboxKey)}
}

func (_c *MockRepositoryAccount_SetKycTx_Call) Run(run func(ctx context.Context, id uuid.UUID, status entity.KycState, inboxKey string)) *MockRepositoryAccount_SetKycTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.KycState), args[3].(string))
	})
	return _c
}

func (_c *MockRepositoryAccount_SetKycTx_Call) Return(_a0 error) *MockRepositoryAccount_SetKycTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryAccount_SetKycTx_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.KycState, string) error) *MockRepositoryAccount_SetKycTx_Call {
	_c.Call.Return(run)
	return _c
}

// SetTierTx provides a mock function with given fields: ctx, id, to, outbox
func (_m *MockRepositoryAccount) SetTierTx(ctx context.Context, id uuid.UUID, to entity.Tier, outbox entity.OutboxEvent) (entity.Account, error) {
	ret := _m.Called(ctx, id, to, outbox)

	if len(ret) == 0 {
		panic("no return value specified for SetTierTx")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.Tier, entity.OutboxEvent) (entity.Account, error)); ok {
		return rf(ctx, id, to, outbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.Tier, entity.OutboxEvent) entity.Account); ok {
		r0 = rf(ctx, id, to, outbox)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.Tier, entity.OutboxEvent) error); ok {
		r1 = rf(ctx, id, to, outbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryAccount_SetTierTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTierTx'
type MockRepositoryAccount_SetTierTx_Call struct {
	*mock.Call
}

// SetTierTx is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - to entity.Tier
//   - outbox entity.OutboxEvent
func (_e *MockRepositoryAccount_Expecter) SetTierTx(ctx interface{}, id interface{}, to interface{}, outbox interface{}) *MockRepositoryAccount_SetTierTx_Call {
	return &MockRepositoryAccount_SetTierTx_Call{Call: _e.mock.On("SetTierTx", ctx, id, to, outbox)}
}

func (_c *MockRepositoryAccount_SetTierTx_Call) Run(run func(ctx context.Context, id uuid.UUID, to entity.Tier, outbox entity.OutboxEvent)) *MockRepositoryAccount_SetTierTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.Tier), args[3].(entity.OutboxEvent))
	})
	return _c
}

func (_c *MockRepositoryAccount_SetTierTx_Call) Return(_a0 entity.Account, _a1 error) *MockRepositoryAccount_SetTierTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryAccount_SetTierTx_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.Tier, entity.OutboxEvent) (entity.Account, error)) *MockRepositoryAccount_SetTierTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryAccount creates a new instance of MockRepositoryAccount. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryAccount {
	mock := &MockRepositoryAccount{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
