// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseAccount is an autogenerated mock type for the UsecaseAccount type
type MockUsecaseAccount struct {
	mock.Mock
}

type MockUsecaseAccount_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseAccount) EXPECT() *MockUsecaseAccount_Expecter {
	return &MockUsecaseAccount_Expecter{mock: &_m.Mock}
}

// ApproveKyc provides a mock function with given fields: ctx, id, idempotencyKey
func (_m *MockUsecaseAccount) ApproveKyc(ctx context.Context, id uuid.UUID, idempotencyKey string) error {
	ret := _m.Called(ctx, id, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for ApproveKyc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseAccount_ApproveKyc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveKyc'
type MockUsecaseAccount_ApproveKyc_Call struct {
	*mock.Call
}

// ApproveKyc is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - idempotencyKey string
func (_e *MockUsecaseAccount_Expecter) ApproveKyc(ctx interface{}, id interface{}, idempotencyKey interface{}) *MockUsecaseAccount_ApproveKyc_Call {
	return &MockUsecaseAccount_ApproveKyc_Call{Call: _e.mock.On("ApproveKyc", ctx, id, idempotencyKey)}
}

func (_c *MockUsecaseAccount_ApproveKyc_Call) Run(run func(ctx context.Context, id uuid.UUID, idempotencyKey string)) *MockUsecaseAccount_ApproveKyc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseAccount_ApproveKyc_Call) Return(_a0 error) *MockUsecaseAccount_ApproveKyc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseAccount_ApproveKyc_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockUsecaseAccount_ApproveKyc_Call {
	_c.Call.Return(run)
	return _c
}

// ElevateToMember provides a mock function with given fields: ctx, id, idempotencyKey
func (_m *MockUsecaseAccount) ElevateToMember(ctx context.Context, id uuid.UUID, idempotencyKey string) error {
	ret := _m.Called(ctx, id, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for ElevateToMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseAccount_ElevateToMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ElevateToMember'
type MockUsecaseAccount_ElevateToMember_Call struct {
	*mock.Call
}

// ElevateToMember is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - idempotencyKey string
func (_e *MockUsecaseAccount_Expecter) ElevateToMember(ctx interface{}, id interface{}, idempotencyKey interface{}) *MockUsecaseAccount_ElevateToMember_Call {
	return &MockUsecaseAccount_ElevateToMember_Call{Call: _e.mock.On("ElevateToMember", ctx, id, idempotencyKey)}
}

func (_c *MockUsecaseAccount_ElevateToMember_Call) Run(run func(ctx context.Context, id uuid.UUID, idempotencyKey string)) *MockUsecaseAccount_ElevateToMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseAccount_ElevateToMember_Call) Return(_a0 error) *MockUsecaseAccount_ElevateToMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseAccount_ElevateToMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockUsecaseAccount_ElevateToMember_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUsecaseAccount) Get(ctx context.Context, id uuid.UUID) (entity.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAccount_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecaseAccount_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseAccount_Expecter) Get(ctx interface{}, id interface{}) *MockUsecaseAccount_Get_Call {
	return &MockUsecaseAccount_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUsecaseAccount_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseAccount_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAccount_Get_Call) Return(_a0 entity.Account, _a1 error) *MockUsecaseAccount_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccount_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Account, error)) *MockUsecaseAccount_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GrantVIP provides a mock function with given fields: ctx, id
func (_m *MockUsecaseAccount) GrantVIP(ctx context.Context, id uuid.UUID) (entity.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GrantVIP")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAccount_GrantVIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrantVIP'
type MockUsecaseAccount_GrantVIP_Call struct {
	*mock.Call
}

// GrantVIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseAccount_Expecter) GrantVIP(ctx interface{}, id interface{}) *MockUsecaseAccount_GrantVIP_Call {
	return &MockUsecaseAccount_GrantVIP_Call{Call: _e.mock.On("GrantVIP", ctx, id)}
}

func (_c *MockUsecaseAccount_GrantVIP_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseAccount_GrantVIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAccount_GrantVIP_Call) Return(_a0 entity.Account, _a1 error) *MockUsecaseAccount_GrantVIP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccount_GrantVIP_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Account, error)) *MockUsecaseAccount_GrantVIP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseAccount creates a new instance of MockUsecaseAccount. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseAccount {
	mock := &MockUsecaseAccount{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
