// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	context "context"

	entity "application/internal/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseAccount is an autogenerated mock type for the UsecaseAccount type
type MockUsecaseAccount struct {
	mock.Mock
}

type MockUsecaseAccount_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseAccount) EXPECT() *MockUsecaseAccount_Expecter {
	return &MockUsecaseAccount_Expecter{mock: &_m.Mock}
}

// ApproveKyc provides a mock function with given fields: ctx, id, idempotencyKey
func (_m *MockUsecaseAccount) ApproveKyc(ctx context.Context, id uuid.UUID, idempotencyKey string) error {
	ret := _m.Called(ctx, id, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for ApproveKyc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseAccount_ApproveKyc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveKyc'
type MockUsecaseAccount_ApproveKyc_Call struct {
	*mock.Call
}

// ApproveKyc is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - idempotencyKey string
func (_e *MockUsecaseAccount_Expecter) ApproveKyc(ctx interface{}, id interface{}, idempotencyKey interface{}) *MockUsecaseAccount_ApproveKyc_Call {
	return &MockUsecaseAccount_ApproveKyc_Call{Call: _e.mock.On("ApproveKyc", ctx, id, idempotencyKey)}
}

func (_c *MockUsecaseAccount_ApproveKyc_Call) Run(run func(ctx context.Context, id uuid.UUID, idempotencyKey string)) *MockUsecaseAccount_ApproveKyc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseAccount_ApproveKyc_Call) Return(_a0 error) *MockUsecaseAccount_ApproveKyc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseAccount_ApproveKyc_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockUsecaseAccount_ApproveKyc_Call {
	_c.Call.Return(run)
	return _c
}

// ElevateToMember provides a mock function with given fields: ctx, id, idempotencyKey
func (_m *MockUsecaseAccount) ElevateToMember(ctx context.Context, id uuid.UUID, idempotencyKey string) error {
	ret := _m.Called(ctx, id, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for ElevateToMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseAccount_ElevateToMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ElevateToMember'
type MockUsecaseAccount_ElevateToMember_Call struct {
	*mock.Call
}

// ElevateToMember is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - idempotencyKey string
func (_e *MockUsecaseAccount_Expecter) ElevateToMember(ctx interface{}, id interface{}, idempotencyKey interface{}) *MockUsecaseAccount_ElevateToMember_Call {
	return &MockUsecaseAccount_ElevateToMember_Call{Call: _e.mock.On("ElevateToMember", ctx, id, idempotencyKey)}
}

func (_c *MockUsecaseAccount_ElevateToMember_Call) Run(run func(ctx context.Context, id uuid.UUID, idempotencyKey string)) *MockUsecaseAccount_ElevateToMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseAccount_ElevateToMember_Call) Return(_a0 error) *MockUsecaseAccount_ElevateToMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseAccount_ElevateToMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockUsecaseAccount_ElevateToMember_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUsecaseAccount) Get(ctx context.Context, id uuid.UUID) (entity.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAccount_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecaseAccount_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseAccount_Expecter) Get(ctx interface{}, id interface{}) *MockUsecaseAccount_Get_Call {
	return &MockUsecaseAccount_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUsecaseAccount_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseAccount_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAccount_Get_Call) Return(_a0 entity.Account, _a1 error) *MockUsecaseAccount_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccount_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Account, error)) *MockUsecaseAccount_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GrantRole provides a mock function with given fields: ctx, id, role, grantedBy
func (_m *MockUsecaseAccount) GrantRole(ctx context.Context, id uuid.UUID, role entity.Role, grantedBy uuid.UUID) (entity.Account, error) {
	ret := _m.Called(ctx, id, role, grantedBy)

	if len(ret) == 0 {
		panic("no return value specified for GrantRole")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.Role, uuid.UUID) (entity.Account, error)); ok {
		return rf(ctx, id, role, grantedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.Role, uuid.UUID) entity.Account); ok {
		r0 = rf(ctx, id, role, grantedBy)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.Role, uuid.UUID) error); ok {
		r1 = rf(ctx, id, role, grantedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAccount_GrantRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrantRole'
type MockUsecaseAccount_GrantRole_Call struct {
	*mock.Call
}

// GrantRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - role entity.Role
//   - grantedBy uuid.UUID
func (_e *MockUsecaseAccount_Expecter) GrantRole(ctx interface{}, id interface{}, role interface{}, grantedBy interface{}) *MockUsecaseAccount_GrantRole_Call {
	return &MockUsecaseAccount_GrantRole_Call{Call: _e.mock.On("GrantRole", ctx, id, role, grantedBy)}
}

func (_c *MockUsecaseAccount_GrantRole_Call) Run(run func(ctx context.Context, id uuid.UUID, role entity.Role, grantedBy uuid.UUID)) *MockUsecaseAccount_GrantRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.Role), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAccount_GrantRole_Call) Return(_a0 entity.Account, _a1 error) *MockUsecaseAccount_GrantRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccount_GrantRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.Role, uuid.UUID) (entity.Account, error)) *MockUsecaseAccount_GrantRole_Call {
	_c.Call.Return(run)
	return _c
}

// GrantVIP provides a mock function with given fields: ctx, id
func (_m *MockUsecaseAccount) GrantVIP(ctx context.Context, id uuid.UUID) (entity.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GrantVIP")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAccount_GrantVIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrantVIP'
type MockUsecaseAccount_GrantVIP_Call struct {
	*mock.Call
}

// GrantVIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseAccount_Expecter) GrantVIP(ctx interface{}, id interface{}) *MockUsecaseAccount_GrantVIP_Call {
	return &MockUsecaseAccount_GrantVIP_Call{Call: _e.mock.On("GrantVIP", ctx, id)}
}

func (_c *MockUsecaseAccount_GrantVIP_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseAccount_GrantVIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAccount_GrantVIP_Call) Return(_a0 entity.Account, _a1 error) *MockUsecaseAccount_GrantVIP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccount_GrantVIP_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Account, error)) *MockUsecaseAccount_GrantVIP_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, f
func (_m *MockUsecaseAccount) ListUsers(ctx context.Context, f biz.UserFilter) ([]entity.Account, int, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []entity.Account
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.UserFilter) ([]entity.Account, int, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, biz.UserFilter) []entity.Account); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, biz.UserFilter) int); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, biz.UserFilter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUsecaseAccount_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUsecaseAccount_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - f biz.UserFilter
func (_e *MockUsecaseAccount_Expecter) ListUsers(ctx interface{}, f interface{}) *MockUsecaseAccount_ListUsers_Call {
	return &MockUsecaseAccount_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, f)}
}

func (_c *MockUsecaseAccount_ListUsers_Call) Run(run func(ctx context.Context, f biz.UserFilter)) *MockUsecaseAccount_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.UserFilter))
	})
	return _c
}

func (_c *MockUsecaseAccount_ListUsers_Call) Return(_a0 []entity.Account, _a1 int, _a2 error) *MockUsecaseAccount_ListUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUsecaseAccount_ListUsers_Call) RunAndReturn(run func(context.Context, biz.UserFilter) ([]entity.Account, int, error)) *MockUsecaseAccount_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRole provides a mock function with given fields: ctx, id, role, by
func (_m *MockUsecaseAccount) RevokeRole(ctx context.Context, id uuid.UUID, role entity.Role, by uuid.UUID) (entity.Account, error) {
	ret := _m.Called(ctx, id, role, by)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRole")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.Role, uuid.UUID) (entity.Account, error)); ok {
		return rf(ctx, id, role, by)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.Role, uuid.UUID) entity.Account); ok {
		r0 = rf(ctx, id, role, by)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.Role, uuid.UUID) error); ok {
		r1 = rf(ctx, id, role, by)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAccount_RevokeRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRole'
type MockUsecaseAccount_RevokeRole_Call struct {
	*mock.Call
}

// RevokeRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - role entity.Role
//   - by uuid.UUID
func (_e *MockUsecaseAccount_Expecter) RevokeRole(ctx interface{}, id interface{}, role interface{}, by interface{}) *MockUsecaseAccount_RevokeRole_Call {
	return &MockUsecaseAccount_RevokeRole_Call{Call: _e.mock.On("RevokeRole", ctx, id, role, by)}
}

func (_c *MockUsecaseAccount_RevokeRole_Call) Run(run func(ctx context.Context, id uuid.UUID, role entity.Role, by uuid.UUID)) *MockUsecaseAccount_RevokeRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.Role), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAccount_RevokeRole_Call) Return(_a0 entity.Account, _a1 error) *MockUsecaseAccount_RevokeRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccount_RevokeRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.Role, uuid.UUID) (entity.Account, error)) *MockUsecaseAccount_RevokeRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, id, p
func (_m *MockUsecaseAccount) UpdateUser(ctx context.Context, id uuid.UUID, p biz.UserPatch) (entity.Account, error) {
	ret := _m.Called(ctx, id, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.UserPatch) (entity.Account, error)); ok {
		return rf(ctx, id, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.UserPatch) entity.Account); ok {
		r0 = rf(ctx, id, p)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, biz.UserPatch) error); ok {
		r1 = rf(ctx, id, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAccount_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUsecaseAccount_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - p biz.UserPatch
func (_e *MockUsecaseAccount_Expecter) UpdateUser(ctx interface{}, id interface{}, p interface{}) *MockUsecaseAccount_UpdateUser_Call {
	return &MockUsecaseAccount_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, id, p)}
}

func (_c *MockUsecaseAccount_UpdateUser_Call) Run(run func(ctx context.Context, id uuid.UUID, p biz.UserPatch)) *MockUsecaseAccount_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(biz.UserPatch))
	})
	return _c
}

func (_c *MockUsecaseAccount_UpdateUser_Call) Return(_a0 entity.Account, _a1 error) *MockUsecaseAccount_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAccount_UpdateUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, biz.UserPatch) (entity.Account, error)) *MockUsecaseAccount_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseAccount creates a new instance of MockUsecaseAccount. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseAccount {
	mock := &MockUsecaseAccount{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
