// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockRepositoryAuth is an autogenerated mock type for the RepositoryAuth type
type MockRepositoryAuth struct {
	mock.Mock
}

type MockRepositoryAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryAuth) EXPECT() *MockRepositoryAuth_Expecter {
	return &MockRepositoryAuth_Expecter{mock: &_m.Mock}
}

// ConsumeOTP provides a mock function with given fields: ctx, mobile, codeHash
func (_m *MockRepositoryAuth) ConsumeOTP(ctx context.Context, mobile string, codeHash string) (bool, error) {
	ret := _m.Called(ctx, mobile, codeHash)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeOTP")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, mobile, codeHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, mobile, codeHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, mobile, codeHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryAuth_ConsumeOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeOTP'
type MockRepositoryAuth_ConsumeOTP_Call struct {
	*mock.Call
}

// ConsumeOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - mobile string
//   - codeHash string
func (_e *MockRepositoryAuth_Expecter) ConsumeOTP(ctx interface{}, mobile interface{}, codeHash interface{}) *MockRepositoryAuth_ConsumeOTP_Call {
	return &MockRepositoryAuth_ConsumeOTP_Call{Call: _e.mock.On("ConsumeOTP", ctx, mobile, codeHash)}
}

func (_c *MockRepositoryAuth_ConsumeOTP_Call) Run(run func(ctx context.Context, mobile string, codeHash string)) *MockRepositoryAuth_ConsumeOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepositoryAuth_ConsumeOTP_Call) Return(_a0 bool, _a1 error) *MockRepositoryAuth_ConsumeOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryAuth_ConsumeOTP_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockRepositoryAuth_ConsumeOTP_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMobileAccountTx provides a mock function with given fields: ctx, id, mobile, outbox
func (_m *MockRepositoryAuth) CreateMobileAccountTx(ctx context.Context, id uuid.UUID, mobile string, outbox entity.OutboxEvent) (entity.Account, error) {
	ret := _m.Called(ctx, id, mobile, outbox)

	if len(ret) == 0 {
		panic("no return value specified for CreateMobileAccountTx")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, entity.OutboxEvent) (entity.Account, error)); ok {
		return rf(ctx, id, mobile, outbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, entity.OutboxEvent) entity.Account); ok {
		r0 = rf(ctx, id, mobile, outbox)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, entity.OutboxEvent) error); ok {
		r1 = rf(ctx, id, mobile, outbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryAuth_CreateMobileAccountTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMobileAccountTx'
type MockRepositoryAuth_CreateMobileAccountTx_Call struct {
	*mock.Call
}

// CreateMobileAccountTx is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - mobile string
//   - outbox entity.OutboxEvent
func (_e *MockRepositoryAuth_Expecter) CreateMobileAccountTx(ctx interface{}, id interface{}, mobile interface{}, outbox interface{}) *MockRepositoryAuth_CreateMobileAccountTx_Call {
	return &MockRepositoryAuth_CreateMobileAccountTx_Call{Call: _e.mock.On("CreateMobileAccountTx", ctx, id, mobile, outbox)}
}

func (_c *MockRepositoryAuth_CreateMobileAccountTx_Call) Run(run func(ctx context.Context, id uuid.UUID, mobile string, outbox entity.OutboxEvent)) *MockRepositoryAuth_CreateMobileAccountTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(entity.OutboxEvent))
	})
	return _c
}

func (_c *MockRepositoryAuth_CreateMobileAccountTx_Call) Return(_a0 entity.Account, _a1 error) *MockRepositoryAuth_CreateMobileAccountTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryAuth_CreateMobileAccountTx_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, entity.OutboxEvent) (entity.Account, error)) *MockRepositoryAuth_CreateMobileAccountTx_Call {
	_c.Call.Return(run)
	return _c
}

// FindAccountByMobile provides a mock function with given fields: ctx, mobile
func (_m *MockRepositoryAuth) FindAccountByMobile(ctx context.Context, mobile string) (entity.Account, bool, error) {
	ret := _m.Called(ctx, mobile)

	if len(ret) == 0 {
		panic("no return value specified for FindAccountByMobile")
	}

	var r0 entity.Account
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Account, bool, error)); ok {
		return rf(ctx, mobile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Account); ok {
		r0 = rf(ctx, mobile)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, mobile)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, mobile)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepositoryAuth_FindAccountByMobile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAccountByMobile'
type MockRepositoryAuth_FindAccountByMobile_Call struct {
	*mock.Call
}

// FindAccountByMobile is a helper method to define mock.On call
//   - ctx context.Context
//   - mobile string
func (_e *MockRepositoryAuth_Expecter) FindAccountByMobile(ctx interface{}, mobile interface{}) *MockRepositoryAuth_FindAccountByMobile_Call {
	return &MockRepositoryAuth_FindAccountByMobile_Call{Call: _e.mock.On("FindAccountByMobile", ctx, mobile)}
}

func (_c *MockRepositoryAuth_FindAccountByMobile_Call) Run(run func(ctx context.Context, mobile string)) *MockRepositoryAuth_FindAccountByMobile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryAuth_FindAccountByMobile_Call) Return(_a0 entity.Account, _a1 bool, _a2 error) *MockRepositoryAuth_FindAccountByMobile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepositoryAuth_FindAccountByMobile_Call) RunAndReturn(run func(context.Context, string) (entity.Account, bool, error)) *MockRepositoryAuth_FindAccountByMobile_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOTP provides a mock function with given fields: ctx, mobile, codeHash, purpose, expiresAt
func (_m *MockRepositoryAuth) InsertOTP(ctx context.Context, mobile string, codeHash string, purpose string, expiresAt time.Time) error {
	ret := _m.Called(ctx, mobile, codeHash, purpose, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for InsertOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) error); ok {
		r0 = rf(ctx, mobile, codeHash, purpose, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryAuth_InsertOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOTP'
type MockRepositoryAuth_InsertOTP_Call struct {
	*mock.Call
}

// InsertOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - mobile string
//   - codeHash string
//   - purpose string
//   - expiresAt time.Time
func (_e *MockRepositoryAuth_Expecter) InsertOTP(ctx interface{}, mobile interface{}, codeHash interface{}, purpose interface{}, expiresAt interface{}) *MockRepositoryAuth_InsertOTP_Call {
	return &MockRepositoryAuth_InsertOTP_Call{Call: _e.mock.On("InsertOTP", ctx, mobile, codeHash, purpose, expiresAt)}
}

func (_c *MockRepositoryAuth_InsertOTP_Call) Run(run func(ctx context.Context, mobile string, codeHash string, purpose string, expiresAt time.Time)) *MockRepositoryAuth_InsertOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRepositoryAuth_InsertOTP_Call) Return(_a0 error) *MockRepositoryAuth_InsertOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryAuth_InsertOTP_Call) RunAndReturn(run func(context.Context, string, string, string, time.Time) error) *MockRepositoryAuth_InsertOTP_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertOAuthTx provides a mock function with given fields: ctx, provider, providerUserID, email, newID, outbox
func (_m *MockRepositoryAuth) UpsertOAuthTx(ctx context.Context, provider string, providerUserID string, email string, newID uuid.UUID, outbox entity.OutboxEvent) (entity.Account, bool, error) {
	ret := _m.Called(ctx, provider, providerUserID, email, newID, outbox)

	if len(ret) == 0 {
		panic("no return value specified for UpsertOAuthTx")
	}

	var r0 entity.Account
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, uuid.UUID, entity.OutboxEvent) (entity.Account, bool, error)); ok {
		return rf(ctx, provider, providerUserID, email, newID, outbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, uuid.UUID, entity.OutboxEvent) entity.Account); ok {
		r0 = rf(ctx, provider, providerUserID, email, newID, outbox)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, uuid.UUID, entity.OutboxEvent) bool); ok {
		r1 = rf(ctx, provider, providerUserID, email, newID, outbox)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, uuid.UUID, entity.OutboxEvent) error); ok {
		r2 = rf(ctx, provider, providerUserID, email, newID, outbox)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepositoryAuth_UpsertOAuthTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertOAuthTx'
type MockRepositoryAuth_UpsertOAuthTx_Call struct {
	*mock.Call
}

// UpsertOAuthTx is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerUserID string
//   - email string
//   - newID uuid.UUID
//   - outbox entity.OutboxEvent
func (_e *MockRepositoryAuth_Expecter) UpsertOAuthTx(ctx interface{}, provider interface{}, providerUserID interface{}, email interface{}, newID interface{}, outbox interface{}) *MockRepositoryAuth_UpsertOAuthTx_Call {
	return &MockRepositoryAuth_UpsertOAuthTx_Call{Call: _e.mock.On("UpsertOAuthTx", ctx, provider, providerUserID, email, newID, outbox)}
}

func (_c *MockRepositoryAuth_UpsertOAuthTx_Call) Run(run func(ctx context.Context, provider string, providerUserID string, email string, newID uuid.UUID, outbox entity.OutboxEvent)) *MockRepositoryAuth_UpsertOAuthTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(uuid.UUID), args[5].(entity.OutboxEvent))
	})
	return _c
}

func (_c *MockRepositoryAuth_UpsertOAuthTx_Call) Return(_a0 entity.Account, _a1 bool, _a2 error) *MockRepositoryAuth_UpsertOAuthTx_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepositoryAuth_UpsertOAuthTx_Call) RunAndReturn(run func(context.Context, string, string, string, uuid.UUID, entity.OutboxEvent) (entity.Account, bool, error)) *MockRepositoryAuth_UpsertOAuthTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryAuth creates a new instance of MockRepositoryAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryAuth {
	mock := &MockRepositoryAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
