// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	biz "application/internal/biz"
	entity "application/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUsecaseAuction is an autogenerated mock type for the UsecaseAuction type
type MockUsecaseAuction struct {
	mock.Mock
}

type MockUsecaseAuction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseAuction) EXPECT() *MockUsecaseAuction_Expecter {
	return &MockUsecaseAuction_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUsecaseAuction) Get(ctx context.Context, id uuid.UUID) (biz.AuctionView, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 biz.AuctionView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (biz.AuctionView, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) biz.AuctionView); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(biz.AuctionView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuction_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecaseAuction_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseAuction_Expecter) Get(ctx interface{}, id interface{}) *MockUsecaseAuction_Get_Call {
	return &MockUsecaseAuction_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUsecaseAuction_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseAuction_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAuction_Get_Call) Return(_a0 biz.AuctionView, _a1 error) *MockUsecaseAuction_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuction_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (biz.AuctionView, error)) *MockUsecaseAuction_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function with given fields: ctx, auctionID, in
func (_m *MockUsecaseAuction) Reserve(ctx context.Context, auctionID uuid.UUID, in biz.ReserveInput) (entity.Reservation, error) {
	ret := _m.Called(ctx, auctionID, in)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 entity.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.ReserveInput) (entity.Reservation, error)); ok {
		return rf(ctx, auctionID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.ReserveInput) entity.Reservation); ok {
		r0 = rf(ctx, auctionID, in)
	} else {
		r0 = ret.Get(0).(entity.Reservation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, biz.ReserveInput) error); ok {
		r1 = rf(ctx, auctionID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuction_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockUsecaseAuction_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uuid.UUID
//   - in biz.ReserveInput
func (_e *MockUsecaseAuction_Expecter) Reserve(ctx interface{}, auctionID interface{}, in interface{}) *MockUsecaseAuction_Reserve_Call {
	return &MockUsecaseAuction_Reserve_Call{Call: _e.mock.On("Reserve", ctx, auctionID, in)}
}

func (_c *MockUsecaseAuction_Reserve_Call) Run(run func(ctx context.Context, auctionID uuid.UUID, in biz.ReserveInput)) *MockUsecaseAuction_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(biz.ReserveInput))
	})
	return _c
}

func (_c *MockUsecaseAuction_Reserve_Call) Return(_a0 entity.Reservation, _a1 error) *MockUsecaseAuction_Reserve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuction_Reserve_Call) RunAndReturn(run func(context.Context, uuid.UUID, biz.ReserveInput) (entity.Reservation, error)) *MockUsecaseAuction_Reserve_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function with given fields: ctx, auctionID, in
func (_m *MockUsecaseAuction) Lock(ctx context.Context, auctionID uuid.UUID, in biz.ReserveInput) (entity.Reservation, error) {
	ret := _m.Called(ctx, auctionID, in)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 entity.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.ReserveInput) (entity.Reservation, error)); ok {
		return rf(ctx, auctionID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, biz.ReserveInput) entity.Reservation); ok {
		r0 = rf(ctx, auctionID, in)
	} else {
		r0 = ret.Get(0).(entity.Reservation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, biz.ReserveInput) error); ok {
		r1 = rf(ctx, auctionID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuction_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockUsecaseAuction_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uuid.UUID
//   - in biz.ReserveInput
func (_e *MockUsecaseAuction_Expecter) Lock(ctx interface{}, auctionID interface{}, in interface{}) *MockUsecaseAuction_Lock_Call {
	return &MockUsecaseAuction_Lock_Call{Call: _e.mock.On("Lock", ctx, auctionID, in)}
}

func (_c *MockUsecaseAuction_Lock_Call) Run(run func(ctx context.Context, auctionID uuid.UUID, in biz.ReserveInput)) *MockUsecaseAuction_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(biz.ReserveInput))
	})
	return _c
}

func (_c *MockUsecaseAuction_Lock_Call) Return(_a0 entity.Reservation, _a1 error) *MockUsecaseAuction_Lock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuction_Lock_Call) RunAndReturn(run func(context.Context, uuid.UUID, biz.ReserveInput) (entity.Reservation, error)) *MockUsecaseAuction_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// Buy provides a mock function with given fields: ctx, auctionID, accountID
func (_m *MockUsecaseAuction) Buy(ctx context.Context, auctionID uuid.UUID, accountID uuid.UUID) (entity.Auction, error) {
	ret := _m.Called(ctx, auctionID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Buy")
	}

	var r0 entity.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (entity.Auction, error)); ok {
		return rf(ctx, auctionID, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) entity.Auction); ok {
		r0 = rf(ctx, auctionID, accountID)
	} else {
		r0 = ret.Get(0).(entity.Auction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, auctionID, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuction_Buy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Buy'
type MockUsecaseAuction_Buy_Call struct {
	*mock.Call
}

// Buy is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uuid.UUID
//   - accountID uuid.UUID
func (_e *MockUsecaseAuction_Expecter) Buy(ctx interface{}, auctionID interface{}, accountID interface{}) *MockUsecaseAuction_Buy_Call {
	return &MockUsecaseAuction_Buy_Call{Call: _e.mock.On("Buy", ctx, auctionID, accountID)}
}

func (_c *MockUsecaseAuction_Buy_Call) Run(run func(ctx context.Context, auctionID uuid.UUID, accountID uuid.UUID)) *MockUsecaseAuction_Buy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAuction_Buy_Call) Return(_a0 entity.Auction, _a1 error) *MockUsecaseAuction_Buy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuction_Buy_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (entity.Auction, error)) *MockUsecaseAuction_Buy_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with given fields: ctx, id
func (_m *MockUsecaseAuction) Open(ctx context.Context, id uuid.UUID) (entity.Auction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 entity.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Auction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Auction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Auction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuction_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockUsecaseAuction_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseAuction_Expecter) Open(ctx interface{}, id interface{}) *MockUsecaseAuction_Open_Call {
	return &MockUsecaseAuction_Open_Call{Call: _e.mock.On("Open", ctx, id)}
}

func (_c *MockUsecaseAuction_Open_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseAuction_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAuction_Open_Call) Return(_a0 entity.Auction, _a1 error) *MockUsecaseAuction_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuction_Open_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Auction, error)) *MockUsecaseAuction_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function with given fields: ctx, id
func (_m *MockUsecaseAuction) Complete(ctx context.Context, id uuid.UUID) (entity.Auction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 entity.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Auction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Auction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Auction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuction_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockUsecaseAuction_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseAuction_Expecter) Complete(ctx interface{}, id interface{}) *MockUsecaseAuction_Complete_Call {
	return &MockUsecaseAuction_Complete_Call{Call: _e.mock.On("Complete", ctx, id)}
}

func (_c *MockUsecaseAuction_Complete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseAuction_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAuction_Complete_Call) Return(_a0 entity.Auction, _a1 error) *MockUsecaseAuction_Complete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuction_Complete_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Auction, error)) *MockUsecaseAuction_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Abort provides a mock function with given fields: ctx, id
func (_m *MockUsecaseAuction) Abort(ctx context.Context, id uuid.UUID) (entity.Auction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Abort")
	}

	var r0 entity.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Auction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Auction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Auction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecaseAuction_Abort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Abort'
type MockUsecaseAuction_Abort_Call struct {
	*mock.Call
}

// Abort is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecaseAuction_Expecter) Abort(ctx interface{}, id interface{}) *MockUsecaseAuction_Abort_Call {
	return &MockUsecaseAuction_Abort_Call{Call: _e.mock.On("Abort", ctx, id)}
}

func (_c *MockUsecaseAuction_Abort_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecaseAuction_Abort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecaseAuction_Abort_Call) Return(_a0 entity.Auction, _a1 error) *MockUsecaseAuction_Abort_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecaseAuction_Abort_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Auction, error)) *MockUsecaseAuction_Abort_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFromLotScheduled provides a mock function with given fields: ctx, in, idempotencyKey
func (_m *MockUsecaseAuction) CreateFromLotScheduled(ctx context.Context, in biz.LotScheduledInput, idempotencyKey string) error {
	ret := _m.Called(ctx, in, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromLotScheduled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.LotScheduledInput, string) error); ok {
		r0 = rf(ctx, in, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseAuction_CreateFromLotScheduled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFromLotScheduled'
type MockUsecaseAuction_CreateFromLotScheduled_Call struct {
	*mock.Call
}

// CreateFromLotScheduled is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.LotScheduledInput
//   - idempotencyKey string
func (_e *MockUsecaseAuction_Expecter) CreateFromLotScheduled(ctx interface{}, in interface{}, idempotencyKey interface{}) *MockUsecaseAuction_CreateFromLotScheduled_Call {
	return &MockUsecaseAuction_CreateFromLotScheduled_Call{Call: _e.mock.On("CreateFromLotScheduled", ctx, in, idempotencyKey)}
}

func (_c *MockUsecaseAuction_CreateFromLotScheduled_Call) Run(run func(ctx context.Context, in biz.LotScheduledInput, idempotencyKey string)) *MockUsecaseAuction_CreateFromLotScheduled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.LotScheduledInput), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseAuction_CreateFromLotScheduled_Call) Return(_a0 error) *MockUsecaseAuction_CreateFromLotScheduled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseAuction_CreateFromLotScheduled_Call) RunAndReturn(run func(context.Context, biz.LotScheduledInput, string) error) *MockUsecaseAuction_CreateFromLotScheduled_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyEscrowLocked provides a mock function with given fields: ctx, in, idempotencyKey
func (_m *MockUsecaseAuction) ApplyEscrowLocked(ctx context.Context, in biz.EscrowLockedInput, idempotencyKey string) error {
	ret := _m.Called(ctx, in, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for ApplyEscrowLocked")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, biz.EscrowLockedInput, string) error); ok {
		r0 = rf(ctx, in, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecaseAuction_ApplyEscrowLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyEscrowLocked'
type MockUsecaseAuction_ApplyEscrowLocked_Call struct {
	*mock.Call
}

// ApplyEscrowLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - in biz.EscrowLockedInput
//   - idempotencyKey string
func (_e *MockUsecaseAuction_Expecter) ApplyEscrowLocked(ctx interface{}, in interface{}, idempotencyKey interface{}) *MockUsecaseAuction_ApplyEscrowLocked_Call {
	return &MockUsecaseAuction_ApplyEscrowLocked_Call{Call: _e.mock.On("ApplyEscrowLocked", ctx, in, idempotencyKey)}
}

func (_c *MockUsecaseAuction_ApplyEscrowLocked_Call) Run(run func(ctx context.Context, in biz.EscrowLockedInput, idempotencyKey string)) *MockUsecaseAuction_ApplyEscrowLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(biz.EscrowLockedInput), args[2].(string))
	})
	return _c
}

func (_c *MockUsecaseAuction_ApplyEscrowLocked_Call) Return(_a0 error) *MockUsecaseAuction_ApplyEscrowLocked_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecaseAuction_ApplyEscrowLocked_Call) RunAndReturn(run func(context.Context, biz.EscrowLockedInput, string) error) *MockUsecaseAuction_ApplyEscrowLocked_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecaseAuction creates a new instance of MockUsecaseAuction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseAuction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseAuction {
	mock := &MockUsecaseAuction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
